import type {
  Franchise,
  Territory,
  City,
  Venue,
  PlayingArea,
  ActivityCategory,
  ExperienceTemplate,
  TemplateVersion,
  ScheduledSession,
  Booking,
  BookingStatus,
  ReservationStatus,
  PaymentStatus,
  BookingType,
  BookingSource,
  Payment,
  Refund,
  IdentityPattern,
  TemporaryIdentity,
  Team,
  TeamAssignment,
  CheckInRecord,
  EmergencyAccessLog,
  LiveSessionState,
  ActivitySegment,
  SegmentResult,
  LiveOperationalNote,
  EquipmentCheckItem,
  SessionCompletionSnapshot,
  CrewMember,
  Shift,
  Tournament,
  TournamentMatch,
  Transaction,
  Incident,
  EvidenceItem,
  Dispute,
  ModerationCase,
  ModerationAction,
  RefundException,
  Signal,
  AuditEvent,
  DayPoint,
  PromoCode,
  SessionStatus
} from "./entities";
import { buildLedgerTransactions } from "./selectors/money";

/* ------------------------------------------------------------------
   DETERMINISTIC NORMALIZED SEED DATA
   Single source of truth for the prototype. Every entity here is
   owned by the central store (lib/store.tsx) and read through
   lib/prototype/repositories.ts. No disconnected mock arrays.
------------------------------------------------------------------- */

export const SEED_FRANCHISES: Franchise[] = [
  {
    id: "f-1",
    name: "Apex Gaming & Sports Central",
    type: "master",
    isInternal: true,
    legalEntity: "Apex Experience OS PVT LTD",
    assignedTerritories: ["hvd-central", "blr-south", "mum-west"],
    franchiseHead: "Noor Fatima",
    revenueShare: 15,
    startDate: "2025-01-01",
    status: "active",
    contactDetails: "central@apexos.com",
    notes: "Platform operator flagship franchise."
  },
  {
    id: "f-2",
    name: "Coastal Sports Collective",
    type: "regional",
    isInternal: false,
    legalEntity: "Coastal Sports LLP",
    assignedTerritories: [],
    franchiseHead: "Ravi Menon",
    revenueShare: 22,
    startDate: "2025-06-01",
    status: "active",
    contactDetails: "ops@coastalsports.in",
    notes: "External regional partner scoping Pune and Kochi corridors."
  }
];

export const SEED_TERRITORIES: Territory[] = [
  { id: "hvd-central", franchiseId: "f-1", name: "Hyderabad Central", type: "urban", state: "Telangana", region: "South-1", managerId: "op-4", status: "active", timezone: "IST (UTC+5:30)", currency: "INR (₹)", contactInfo: "hyd-ops@experienceos.com", notes: "Highest tonight capacity." },
  { id: "blr-south", franchiseId: "f-1", name: "Bengaluru South", type: "urban", state: "Karnataka", region: "South-2", managerId: "op-10", status: "active", timezone: "IST (UTC+5:30)", currency: "INR (₹)", contactInfo: "blr-ops@experienceos.com", notes: "Core tech crew center." },
  { id: "mum-west", franchiseId: "f-1", name: "Mumbai West", type: "urban", state: "Maharashtra", region: "West-1", managerId: "op-3", status: "active", timezone: "IST (UTC+5:30)", currency: "INR (₹)", contactInfo: "bom-ops@experienceos.com", notes: "High weather vulnerability during monsoon." }
];

export const SEED_CITIES: City[] = [
  { id: "c-hyd", territoryId: "hvd-central", name: "Hyderabad", state: "Telangana", launchDate: "2025-01-10", managerId: "op-4", supportedCategories: ["cat-cricket", "cat-badminton", "cat-tt"], status: "active", notes: "Active operations since launch." },
  { id: "c-blr", territoryId: "blr-south", name: "Bengaluru", state: "Karnataka", launchDate: "2025-02-15", managerId: "op-10", supportedCategories: ["cat-cricket", "cat-badminton", "cat-board"], status: "active", notes: "Expanding venues." },
  { id: "c-mum", territoryId: "mum-west", name: "Mumbai", state: "Maharashtra", launchDate: "2025-03-20", managerId: "op-3", supportedCategories: ["cat-cricket", "cat-badminton"], status: "active", notes: "Weather alert policies active." }
];

export const SEED_VENUES: Venue[] = [
  {
    id: "v-1",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    name: "Hitex Sports Arena",
    address: "Hitex Exhibition Center, Madhapur, Hyderabad",
    contactPerson: "Kiran Rao",
    contactNumber: "+91 98765 43210",
    type: "arena",
    operatingHours: "06:00 - 23:30",
    supportedActivities: ["cat-badminton"],
    safetyCapacity: 120,
    staffCapacity: 10,
    spectatorAllowance: 50,
    equipmentAvailable: ["Badminton Rackets", "Nylon Shuttles", "Netting"],
    accessibility: true,
    parking: true,
    washrooms: true,
    lighting: true,
    isIndoor: true,
    weatherDependent: false,
    costPerSlot: 1200,
    revenueModel: "fixed",
    cancellationTerms: "24h prior full refund",
    emergencyExits: "2 exits in Hall A, 2 in Hall B",
    firstAid: true,
    safetyContact: "+91 98765 43211",
    incidentNotes: "All staff trained in basic medical response.",
    verificationStatus: "verified",
    status: "ready"
  },
  {
    id: "v-2",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    name: "Gachibowli Indoor Club",
    address: "ISB Road, Gachibowli, Hyderabad",
    contactPerson: "Srinivas G",
    contactNumber: "+91 98765 43220",
    type: "club",
    operatingHours: "07:00 - 23:00",
    supportedActivities: ["cat-tt", "cat-foosball"],
    safetyCapacity: 80,
    staffCapacity: 6,
    spectatorAllowance: 20,
    equipmentAvailable: ["TT Paddles", "Plastic Balls", "Stiga Tables", "Foosball table"],
    accessibility: true,
    parking: true,
    washrooms: true,
    lighting: true,
    isIndoor: true,
    weatherDependent: false,
    costPerSlot: 800,
    revenueModel: "fixed",
    cancellationTerms: "12h prior full refund",
    emergencyExits: "1 main lobby exit, 1 fire exit",
    firstAid: true,
    safetyContact: "+91 98765 43221",
    incidentNotes: "No major medical alerts.",
    verificationStatus: "verified",
    status: "ready"
  },
  {
    id: "v-3",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    name: "Jubilee Grounds",
    address: "Road No. 10, Jubilee Hills, Hyderabad",
    contactPerson: "Ram Charan",
    contactNumber: "+91 98765 43230",
    type: "turf",
    operatingHours: "05:00 - 01:00",
    supportedActivities: ["cat-cricket"],
    safetyCapacity: 150,
    staffCapacity: 8,
    spectatorAllowance: 80,
    equipmentAvailable: ["Cricket Bats", "Tennis Balls", "Wickets", "Stumps"],
    accessibility: false,
    parking: true,
    washrooms: true,
    lighting: true,
    isIndoor: false,
    weatherDependent: true,
    costPerSlot: 1500,
    revenueModel: "fixed",
    cancellationTerms: "Weather cancel eligible",
    emergencyExits: "Open ground perimeter exits",
    firstAid: true,
    safetyContact: "+91 98765 43231",
    incidentNotes: "High rain impact zone.",
    verificationStatus: "verified",
    status: "ready"
  },
  {
    id: "v-4",
    territoryId: "blr-south",
    cityId: "c-blr",
    name: "Koramangala Courts",
    address: "80 Feet Road, Koramangala, Bengaluru",
    contactPerson: "Nikhil K",
    contactNumber: "+91 98765 43240",
    type: "turf",
    operatingHours: "06:00 - 00:00",
    supportedActivities: ["cat-cricket"],
    safetyCapacity: 100,
    staffCapacity: 5,
    spectatorAllowance: 30,
    equipmentAvailable: ["Cricket Bats", "Balls", "Pads"],
    accessibility: true,
    parking: false,
    washrooms: true,
    lighting: true,
    isIndoor: false,
    weatherDependent: true,
    costPerSlot: 1400,
    revenueModel: "fixed",
    cancellationTerms: "Weather cancel eligible",
    emergencyExits: "2 exits on side alleys",
    firstAid: true,
    safetyContact: "+91 98765 43241",
    incidentNotes: "Near local clinic.",
    verificationStatus: "verified",
    status: "ready"
  },
  {
    id: "v-5",
    territoryId: "blr-south",
    cityId: "c-blr",
    name: "Indiranagar Pavilion",
    address: "100 Feet Road, Indiranagar, Bengaluru",
    contactPerson: "Rohan M",
    contactNumber: "+91 98765 43250",
    type: "club",
    operatingHours: "08:00 - 22:00",
    supportedActivities: ["cat-board"],
    safetyCapacity: 60,
    staffCapacity: 4,
    spectatorAllowance: 10,
    equipmentAvailable: ["Board games collection"],
    accessibility: true,
    parking: true,
    washrooms: true,
    lighting: true,
    isIndoor: true,
    weatherDependent: false,
    costPerSlot: 500,
    revenueModel: "fixed",
    cancellationTerms: "24h prior full refund",
    emergencyExits: "1 main exit",
    firstAid: true,
    safetyContact: "+91 98765 43251",
    incidentNotes: "Air conditioned hall.",
    verificationStatus: "verified",
    status: "maintenance"
  },
  {
    id: "v-6",
    territoryId: "mum-west",
    cityId: "c-mum",
    name: "Andheri Sports Dome",
    address: "Link Road, Andheri West, Mumbai",
    contactPerson: "Vivek S",
    contactNumber: "+91 98765 43260",
    type: "arena",
    operatingHours: "06:00 - 02:00",
    supportedActivities: ["cat-cricket", "cat-badminton"],
    safetyCapacity: 140,
    staffCapacity: 8,
    spectatorAllowance: 60,
    equipmentAvailable: ["Cricket Bats", "Tennis Balls", "Shuttles"],
    accessibility: true,
    parking: true,
    washrooms: true,
    lighting: true,
    isIndoor: true,
    weatherDependent: false,
    costPerSlot: 1800,
    revenueModel: "fixed",
    cancellationTerms: "12h prior full refund",
    emergencyExits: "3 exit doors",
    firstAid: true,
    safetyContact: "+91 98765 43261",
    incidentNotes: "Weatherproof indoor dome.",
    verificationStatus: "verified",
    status: "ready"
  }
];

export const SEED_PLAYING_AREAS: PlayingArea[] = [
  { id: "pa-1", venueId: "v-1", name: "Court 1", activityCompatibility: ["cat-badminton"], maxCapacity: 4, staffCapacity: 1, spectatorCapacity: 10, equipment: ["Posts", "Nets"], operatingHours: "06:00 - 23:30", status: "active", restrictions: "Non-marking shoes mandatory" },
  { id: "pa-2", venueId: "v-1", name: "Court 2", activityCompatibility: ["cat-badminton"], maxCapacity: 4, staffCapacity: 1, spectatorCapacity: 10, equipment: ["Posts", "Nets"], operatingHours: "06:00 - 23:30", status: "active", restrictions: "Non-marking shoes mandatory" },
  { id: "pa-3", venueId: "v-2", name: "Hall A Table 1", activityCompatibility: ["cat-tt"], maxCapacity: 4, staffCapacity: 1, spectatorCapacity: 5, equipment: ["Stiga Table"], operatingHours: "07:00 - 23:00", status: "active", restrictions: "No food near table" },
  { id: "pa-4", venueId: "v-3", name: "Pitch 1", activityCompatibility: ["cat-cricket"], maxCapacity: 16, staffCapacity: 2, spectatorCapacity: 40, equipment: ["Turf Nets", "Wickets"], operatingHours: "05:00 - 01:00", status: "active", restrictions: "Molded studs allowed only" },
  { id: "pa-5", venueId: "v-4", name: "Court A", activityCompatibility: ["cat-cricket"], maxCapacity: 14, staffCapacity: 2, spectatorCapacity: 20, equipment: ["Nets"], operatingHours: "06:00 - 00:00", status: "active", restrictions: "Sports sneakers only" },
  { id: "pa-6", venueId: "v-5", name: "Main Hall Table 1", activityCompatibility: ["cat-board"], maxCapacity: 8, staffCapacity: 1, spectatorCapacity: 5, equipment: ["Table and Chairs"], operatingHours: "08:00 - 22:00", status: "active", restrictions: "None" },
  { id: "pa-7", venueId: "v-6", name: "Turf 1", activityCompatibility: ["cat-cricket", "cat-badminton"], maxCapacity: 16, staffCapacity: 2, spectatorCapacity: 30, equipment: ["Indoor netting"], operatingHours: "06:00 - 02:00", status: "active", restrictions: "Sports sneakers only" }
];

export const SEED_CATEGORIES: ActivityCategory[] = [
  { id: "cat-cricket", name: "Box Cricket", description: "Indoor or net-bound cricket matching high operational intensity.", icon: "Cricket", visualTreatment: "accent-warm", riskLevel: "medium", isIndoor: false, equipmentRequirements: ["Wickets", "Bats", "Tennis balls"], defaultStaffing: ["coordinator", "referee"], defaultDuration: 120, defaultAgeMin: 12, defaultAgeMax: 60, defaultParticipantsMin: 8, defaultParticipantsMax: 16, shortCode: "CRICKET", status: "active", traits: ["competitive", "team", "outdoor"], defaultTargetParticipants: 12, defaultTeamSize: 6, defaultCoordinatorRequired: true, refereeRequirement: "required", activitySpecialistRequired: true, safetyContactRequired: true, participantRequirements: ["Sports footwear", "Water bottle"], weatherDependency: true, accessibilityNotes: "Turf surfaces; step-free access varies by venue.", venueCompat: { indoorOutdoor: "outdoor", minAreaCapacity: 100, lightingRequired: true, washroomRequired: true, requiredCapabilities: ["firstAid"], requiredEquipment: ["Cricket Bats"] }, createdAt: "2026-05-10", updatedAt: "2026-07-30" },
  { id: "cat-badminton", name: "Badminton", description: "Social singles and doubles court games.", icon: "Activity", visualTreatment: "accent-ok", riskLevel: "low", isIndoor: true, equipmentRequirements: ["Rackets", "Shuttlecocks", "Net"], defaultStaffing: ["coordinator"], defaultDuration: 60, defaultAgeMin: 8, defaultAgeMax: 65, defaultParticipantsMin: 2, defaultParticipantsMax: 4, shortCode: "BADMINTON", status: "active", traits: ["social", "doubles", "indoor"], defaultTargetParticipants: 4, defaultTeamSize: 2, defaultCoordinatorRequired: true, refereeRequirement: "none", activitySpecialistRequired: false, safetyContactRequired: false, participantRequirements: ["Non-marking shoes", "Racket"], weatherDependency: false, accessibilityNotes: "Indoor courts with step-free access.", venueCompat: { indoorOutdoor: "indoor", minAreaCapacity: 60, lightingRequired: true, washroomRequired: true, requiredCapabilities: ["accessibility"], requiredEquipment: ["Net"] }, createdAt: "2026-05-10", updatedAt: "2026-07-29" },
  { id: "cat-tt", name: "Table Tennis", description: "Fast paced indoor matches.", icon: "Gamepad2", visualTreatment: "accent-cool", riskLevel: "low", isIndoor: true, equipmentRequirements: ["TT Table", "Paddles", "Balls"], defaultStaffing: ["coordinator"], defaultDuration: 60, defaultAgeMin: 8, defaultAgeMax: 70, defaultParticipantsMin: 2, defaultParticipantsMax: 8, shortCode: "TT", status: "active", traits: ["social", "indoor", "fast"], defaultTargetParticipants: 8, defaultTeamSize: 1, defaultCoordinatorRequired: true, refereeRequirement: "none", activitySpecialistRequired: false, safetyContactRequired: false, participantRequirements: ["Comfortable shoes"], weatherDependency: false, accessibilityNotes: "Tables at ground level.", venueCompat: { indoorOutdoor: "indoor", minAreaCapacity: 40, lightingRequired: true, washroomRequired: true, requiredEquipment: ["Paddles"] }, createdAt: "2026-05-12", updatedAt: "2026-07-29" },
  { id: "cat-board", name: "Board Games", description: "Casual tabletop night mixers.", icon: "Dices", visualTreatment: "accent-neutral", riskLevel: "low", isIndoor: true, equipmentRequirements: ["Board game box"], defaultStaffing: ["coordinator"], defaultDuration: 180, defaultAgeMin: 10, defaultAgeMax: 80, defaultParticipantsMin: 4, defaultParticipantsMax: 12, shortCode: "BOARD", status: "active", traits: ["casual", "indoor", "social"], defaultTargetParticipants: 8, defaultTeamSize: 4, defaultCoordinatorRequired: true, refereeRequirement: "none", activitySpecialistRequired: false, safetyContactRequired: false, participantRequirements: ["None"], weatherDependency: false, accessibilityNotes: "Seated activity, fully accessible.", venueCompat: { indoorOutdoor: "indoor", minAreaCapacity: 40, lightingRequired: false, washroomRequired: true, requiredEquipment: ["Board game box"] }, createdAt: "2026-05-15", updatedAt: "2026-07-28" },
  { id: "cat-foosball", name: "Foosball", description: "Table foosball socials with king-of-the-table rotations.", icon: "Gamepad2", visualTreatment: "accent-cool", riskLevel: "low", isIndoor: true, equipmentRequirements: ["Foosball table", "Balls"], defaultStaffing: ["coordinator"], defaultDuration: 60, defaultAgeMin: 10, defaultAgeMax: 60, defaultParticipantsMin: 4, defaultParticipantsMax: 8, shortCode: "FOOSBALL", status: "active", traits: ["social", "indoor", "quick"], defaultTargetParticipants: 8, defaultTeamSize: 2, defaultCoordinatorRequired: true, refereeRequirement: "none", activitySpecialistRequired: false, safetyContactRequired: false, participantRequirements: ["None"], weatherDependency: false, accessibilityNotes: "Standing activity; table at standard height.", venueCompat: { indoorOutdoor: "indoor", minAreaCapacity: 30, lightingRequired: true, washroomRequired: true, requiredEquipment: ["Foosball table"] }, createdAt: "2026-05-18", updatedAt: "2026-07-27" }
];

export const SEED_TEMPLATES: ExperienceTemplate[] = [
  {
    id: "et-1",
    categoryId: "cat-cricket",
    name: "Evening Box Cricket Match",
    shortDesc: "High energy 8v8 box cricket mixer under the lights.",
    fullDesc: "Our signature late-night format. Join as an individual and get randomly sorted into a team. Matches are played on premium synthetic turf nets with high visibility tennis balls.",
    objective: "Get 2 teams of 8 to compete and complete 12 overs per side.",
    promise: "Minimum 3 overs batting or bowling per participant.",
    status: "active",
    format: "mixed",
    isTournament: false,
    ageMin: 14,
    ageMax: 50,
    verificationRequired: false,
    minParticipants: 8,
    targetParticipants: 12,
    maxParticipants: 12,
    teamSize: 6,
    numTeams: 2,
    spectatorAllowance: 20,
    compSlots: 0,
    blockedSlots: 0,
    duration: 120,
    checkInWindow: 15,
    bookingOpenDays: 5,
    bookingCloseHours: 2,
    revealHoursBefore: 1,
    lateArrivalMins: 10,
    completionBufferMins: 15,
    basePrice: 499,
    taxAmount: 90,
    platformFee: 29,
    venueCost: 1500,
    equipmentCost: 200,
    promoEligible: true,
    refundPolicyTemplate: "Full refund 12h prior",
    requiredRoles: ["coordinator", "referee"],
    coordinatorsCount: 1,
    refereeRequired: true,
    safetyContactRequired: true,
    equipmentChecklist: ["2 Cricket Bats", "6 Tennis Balls", "1 Set Wickets"],
    participantChecklist: ["Sports footwear", "Water bottle"],
    weatherDependency: true,
    cancellationThreshold: 8,
    anonymousJoinedCount: false,
    tempIdFormat: "CR-##",
    aliasStyle: "CricketLegend",
    teamAssignmentRule: "random-balance",
    revealTimeMinsBefore: 60,
    infoRevealed: ["Team name", "Temporary ID", "Playing field"],
    infoNeverRevealed: ["Legal identity", "Phone number"],
    entryType: "individual",
    competitiveLevel: "competitive",
    eligibilityNote: "Open to all ages 14-50",
    coverMediaPlaceholder: "cricket-turf-night.jpg",
    createdAt: "2026-06-01",
    updatedAt: "2026-07-22",
    createdBy: "op-2",
    substitutes: 2,
    waitlistDefault: true,
    waitlistOfferExpiryMins: 90,
    minParticipantDecisionTime: 12,
    recurrenceSuitability: "weekly",
    staffingCost: 600,
    compBookingAllowance: 1,
    leadCoordinatorRequired: true,
    showJoinedCountBeforeReveal: false,
    teamAssignmentMethod: "balanced",
    preRevealPreview: "You'll discover your team and field location right before reveal.",
    postRevealPreview: "Team rosters and field details unlock at reveal time.",
    venueCompat: { indoorOutdoorNeed: "outdoor", minAreaCapacity: 100, lighting: true, requiredVenueVerification: "verified" },
    cancellationPolicyTemplate: "Full refund 12h prior",
    noShowTreatment: "Marked no-show, blocked from next 2 sessions",
    lateArrivalTreatment: "10 min late arrival window",
    behaviourRules: ["Respect umpire decisions", "No abusive language"],
    safetyLevel: "medium",
    incidentEscalationRequired: true,
    prizeVerificationRequired: false,
    legalReviewStatus: "approved",
    dataRetentionPlaceholder: "30 days per data-retention policy (prototype placeholder)"
  },
  {
    id: "et-2",
    categoryId: "cat-badminton",
    name: "Night Badminton League Mixer",
    shortDesc: "Rapid social doubles rotating ladder mixer.",
    fullDesc: "Casual social doubles mixer. Non-stop doubles rotation on premium indoor wooden courts.",
    objective: "Social mixer doubles tournament rotation.",
    promise: "Minimum 4 matches playing time.",
    status: "active",
    format: "mixed",
    isTournament: true,
    ageMin: 12,
    ageMax: 60,
    verificationRequired: false,
    minParticipants: 10,
    targetParticipants: 16,
    maxParticipants: 16,
    teamSize: 2,
    numTeams: 8,
    spectatorAllowance: 10,
    compSlots: 1,
    blockedSlots: 0,
    duration: 120,
    checkInWindow: 10,
    bookingOpenDays: 7,
    bookingCloseHours: 1,
    revealHoursBefore: 2,
    lateArrivalMins: 5,
    completionBufferMins: 10,
    basePrice: 349,
    taxAmount: 63,
    platformFee: 18,
    venueCost: 1200,
    equipmentCost: 300,
    promoEligible: true,
    refundPolicyTemplate: "Full refund 24h prior",
    requiredRoles: ["coordinator"],
    coordinatorsCount: 1,
    refereeRequired: false,
    safetyContactRequired: false,
    equipmentChecklist: ["3 Tubes Shuttles", "Doubles Net"],
    participantChecklist: ["Non-marking shoes", "Badminton racket"],
    weatherDependency: false,
    cancellationThreshold: 10,
    anonymousJoinedCount: false,
    tempIdFormat: "BM-##",
    aliasStyle: "SmashChampion",
    teamAssignmentRule: "random",
    revealTimeMinsBefore: 120,
    infoRevealed: ["Team partner", "Court schedule"],
    infoNeverRevealed: ["Opponent phone number"],
    entryType: "individual",
    competitiveLevel: "social-competitive",
    coverMediaPlaceholder: "badminton-courts-night.jpg",
    createdAt: "2026-06-05",
    updatedAt: "2026-07-25",
    createdBy: "op-2",
    substitutes: 2,
    waitlistDefault: true,
    waitlistOfferExpiryMins: 60,
    minParticipantDecisionTime: 6,
    recurrenceSuitability: "fortnightly",
    staffingCost: 450,
    compBookingAllowance: 1,
    leadCoordinatorRequired: true,
    teamAssignmentMethod: "random",
    preRevealPreview: "Partners drawn at reveal time.",
    postRevealPreview: "Partner and court schedule visible after reveal.",
    cancellationPolicyTemplate: "Full refund 24h prior",
    noShowTreatment: "Marked no-show",
    lateArrivalTreatment: "5 min late arrival window",
    safetyLevel: "low",
    incidentEscalationRequired: false,
    prizeVerificationRequired: true,
    legalReviewStatus: "approved",
    dataRetentionPlaceholder: "45 days for tournament records (prototype placeholder)"
  },
  {
    id: "et-3",
    categoryId: "cat-badminton",
    name: "Women's Social Badminton",
    shortDesc: "Women-only social doubles evening.",
    fullDesc: "A women-only social doubles session. Rotating partners, friendly scoring, zero pressure.",
    objective: "Social mixer with rotating doubles partners.",
    promise: "Minimum 5 games in 2 hours.",
    status: "active",
    format: "women",
    isTournament: false,
    ageMin: 18,
    ageMax: 55,
    verificationRequired: true,
    minParticipants: 8,
    targetParticipants: 12,
    maxParticipants: 12,
    teamSize: 2,
    numTeams: 6,
    spectatorAllowance: 5,
    compSlots: 0,
    blockedSlots: 0,
    duration: 120,
    checkInWindow: 10,
    bookingOpenDays: 4,
    bookingCloseHours: 1,
    revealHoursBefore: 1,
    lateArrivalMins: 5,
    completionBufferMins: 10,
    basePrice: 299,
    taxAmount: 54,
    platformFee: 15,
    venueCost: 1000,
    equipmentCost: 200,
    promoEligible: true,
    refundPolicyTemplate: "Full refund 12h prior",
    requiredRoles: ["coordinator", "safety"],
    coordinatorsCount: 1,
    refereeRequired: false,
    safetyContactRequired: true,
    equipmentChecklist: ["4 Tubes Shuttles", "Net"],
    participantChecklist: ["Non-marking shoes"],
    weatherDependency: false,
    cancellationThreshold: 8,
    anonymousJoinedCount: true,
    tempIdFormat: "WBM-##",
    aliasStyle: "FeatherStorm",
    teamAssignmentRule: "random",
    revealTimeMinsBefore: 60,
    infoRevealed: ["Partner", "Court number"],
    infoNeverRevealed: ["Phone number"],
    entryType: "individual",
    competitiveLevel: "social",
    womenCoordinatorPreference: true,
    coverMediaPlaceholder: "badminton-womens-social.jpg",
    createdAt: "2026-06-15",
    updatedAt: "2026-07-18",
    createdBy: "op-10",
    substitutes: 2,
    waitlistDefault: true,
    waitlistOfferExpiryMins: 60,
    minParticipantDecisionTime: 8,
    recurrenceSuitability: "weekly",
    staffingCost: 350,
    showJoinedCountBeforeReveal: false,
    mutualConnectionDeferred: true,
    preRevealPreview: "Participants stay anonymous — joined count hidden until reveal.",
    postRevealPreview: "Names and partners unlock at reveal.",
    cancellationPolicyTemplate: "Full refund 12h prior",
    noShowTreatment: "Marked no-show",
    lateArrivalTreatment: "5 min late arrival window",
    behaviourRules: ["Respect boundaries", "Zero tolerance for harassment"],
    safetyLevel: "low",
    incidentEscalationRequired: true,
    legalReviewStatus: "approved",
    dataRetentionPlaceholder: "30 days; identity masked (prototype placeholder)"
  },
  {
    id: "et-4",
    categoryId: "cat-tt",
    name: "Rooftop Table Tennis Social",
    shortDesc: "Fast paced TT ladder on open-air tables.",
    fullDesc: "Open-air table tennis social with a rotating ladder. Bring your spin; leave the stress.",
    objective: "Rotating TT ladder social.",
    promise: "Minimum 8 games.",
    status: "active",
    format: "mixed",
    isTournament: false,
    ageMin: 10,
    ageMax: 60,
    verificationRequired: false,
    minParticipants: 6,
    targetParticipants: 8,
    maxParticipants: 8,
    teamSize: 1,
    numTeams: 8,
    spectatorAllowance: 8,
    compSlots: 0,
    blockedSlots: 0,
    duration: 90,
    checkInWindow: 10,
    bookingOpenDays: 3,
    bookingCloseHours: 1,
    revealHoursBefore: 1,
    lateArrivalMins: 5,
    completionBufferMins: 10,
    basePrice: 249,
    taxAmount: 45,
    platformFee: 12,
    venueCost: 600,
    equipmentCost: 100,
    promoEligible: false,
    refundPolicyTemplate: "Full refund 12h prior",
    requiredRoles: ["coordinator"],
    coordinatorsCount: 1,
    refereeRequired: false,
    safetyContactRequired: false,
    equipmentChecklist: ["8 Paddles", "6 Plastic Balls"],
    participantChecklist: ["Comfortable shoes"],
    weatherDependency: true,
    cancellationThreshold: 6,
    anonymousJoinedCount: false,
    tempIdFormat: "TT-##",
    aliasStyle: "PaddlePace",
    teamAssignmentRule: "random",
    revealTimeMinsBefore: 60,
    infoRevealed: ["Ladder position"],
    infoNeverRevealed: ["Phone number"],
    entryType: "individual",
    competitiveLevel: "social",
    coverMediaPlaceholder: "tt-rooftop.jpg",
    createdAt: "2026-06-20",
    updatedAt: "2026-07-27",
    createdBy: "op-2",
    substitutes: 1,
    waitlistDefault: false,
    staffingCost: 250,
    showJoinedCountBeforeReveal: true,
    preRevealPreview: "Joined count visible before reveal.",
    postRevealPreview: "Ladder details visible after reveal.",
    safetyLevel: "low",
    legalReviewStatus: "approved",
    dataRetentionPlaceholder: "30 days (prototype placeholder)"
  },
  {
    id: "et-5",
    categoryId: "cat-board",
    name: "Board Games Parlour",
    shortDesc: "Casual tabletop mixer with curated games.",
    fullDesc: "A relaxed tabletop night. Hosts rotate the collection, players rotate the tables.",
    objective: "Casual tabletop mixer.",
    promise: "Minimum 3 different games.",
    status: "active",
    format: "mixed",
    isTournament: false,
    ageMin: 12,
    ageMax: 60,
    verificationRequired: false,
    minParticipants: 4,
    targetParticipants: 10,
    maxParticipants: 10,
    teamSize: 2,
    numTeams: 5,
    spectatorAllowance: 2,
    compSlots: 0,
    blockedSlots: 0,
    duration: 180,
    checkInWindow: 10,
    bookingOpenDays: 6,
    bookingCloseHours: 2,
    revealHoursBefore: 1,
    lateArrivalMins: 10,
    completionBufferMins: 15,
    basePrice: 199,
    taxAmount: 36,
    platformFee: 10,
    venueCost: 400,
    equipmentCost: 80,
    promoEligible: true,
    refundPolicyTemplate: "Full refund 24h prior",
    requiredRoles: ["coordinator"],
    coordinatorsCount: 1,
    refereeRequired: false,
    safetyContactRequired: false,
    equipmentChecklist: ["Game collection", "Score sheets"],
    participantChecklist: ["None"],
    weatherDependency: false,
    cancellationThreshold: 4,
    anonymousJoinedCount: false,
    tempIdFormat: "BG-##",
    aliasStyle: "TabletopKnight",
    teamAssignmentRule: "random",
    revealTimeMinsBefore: 60,
    infoRevealed: ["Table number"],
    infoNeverRevealed: ["Phone number"],
    entryType: "individual",
    competitiveLevel: "casual",
    coverMediaPlaceholder: "boardgames-parlour.jpg",
    createdAt: "2026-06-22",
    updatedAt: "2026-07-26",
    createdBy: "op-2",
    substitutes: 2,
    waitlistDefault: true,
    staffingCost: 300,
    showJoinedCountBeforeReveal: true,
    preRevealPreview: "Table number revealed at check-in.",
    postRevealPreview: "Table and host visible after reveal.",
    safetyLevel: "low",
    legalReviewStatus: "approved",
    dataRetentionPlaceholder: "30 days (prototype placeholder)"
  },
  {
    id: "et-6",
    categoryId: "cat-foosball",
    name: "Foosball Fiesta",
    shortDesc: "King-of-the-table foosball social mixer.",
    fullDesc: "Rotating king-of-the-table foosball rounds. Quick-fire games, friendly scores, fast rotations.",
    objective: "Rotating foosball social with a running leaderboard.",
    promise: "Minimum 6 games of table time.",
    status: "active",
    format: "mixed",
    isTournament: false,
    ageMin: 10,
    ageMax: 60,
    verificationRequired: false,
    minParticipants: 4,
    targetParticipants: 8,
    maxParticipants: 8,
    teamSize: 2,
    numTeams: 4,
    spectatorAllowance: 4,
    compSlots: 0,
    blockedSlots: 0,
    duration: 60,
    checkInWindow: 10,
    bookingOpenDays: 3,
    bookingCloseHours: 1,
    revealHoursBefore: 1,
    lateArrivalMins: 5,
    completionBufferMins: 10,
    basePrice: 179,
    taxAmount: 32,
    platformFee: 9,
    venueCost: 300,
    equipmentCost: 50,
    promoEligible: true,
    refundPolicyTemplate: "Full refund 12h prior",
    requiredRoles: ["coordinator"],
    coordinatorsCount: 1,
    refereeRequired: false,
    safetyContactRequired: false,
    equipmentChecklist: ["Foosball table", "Balls"],
    participantChecklist: ["None"],
    weatherDependency: false,
    cancellationThreshold: 4,
    anonymousJoinedCount: false,
    tempIdFormat: "FS-##",
    aliasStyle: "TableTitan",
    teamAssignmentRule: "random",
    revealTimeMinsBefore: 60,
    infoRevealed: ["Ladder position"],
    infoNeverRevealed: ["Phone number"],
    entryType: "individual",
    competitiveLevel: "social",
    coverMediaPlaceholder: "foosball-fiesta.jpg",
    createdAt: "2026-06-25",
    updatedAt: "2026-07-24",
    createdBy: "op-2",
    substitutes: 1,
    waitlistDefault: false,
    staffingCost: 200,
    showJoinedCountBeforeReveal: true,
    preRevealPreview: "Joined count visible before reveal.",
    postRevealPreview: "Ladder position revealed after reveal.",
    safetyLevel: "low",
    legalReviewStatus: "approved",
    dataRetentionPlaceholder: "30 days (prototype placeholder)"
  },
  {
    id: "et-7",
    categoryId: "cat-cricket",
    name: "Sunrise Cricket Academy",
    shortDesc: "Draft — early-morning coaching net slot.",
    fullDesc: "Planned coaching-led net session with skill stations. Not yet scheduled anywhere.",
    objective: "Deliver a structured 90-minute coaching net for beginners.",
    promise: "4 skill stations and one supervised match simulation.",
    status: "draft",
    format: "open",
    isTournament: false,
    ageMin: 10,
    ageMax: 40,
    verificationRequired: false,
    minParticipants: 6,
    targetParticipants: 12,
    maxParticipants: 12,
    teamSize: 6,
    numTeams: 2,
    spectatorAllowance: 10,
    compSlots: 0,
    blockedSlots: 0,
    duration: 90,
    checkInWindow: 15,
    bookingOpenDays: 5,
    bookingCloseHours: 2,
    revealHoursBefore: 2,
    lateArrivalMins: 10,
    completionBufferMins: 15,
    basePrice: 399,
    taxAmount: 72,
    platformFee: 20,
    venueCost: 1200,
    equipmentCost: 300,
    promoEligible: true,
    refundPolicyTemplate: "Full refund 24h prior",
    requiredRoles: ["coordinator", "specialist"],
    coordinatorsCount: 2,
    refereeRequired: false,
    safetyContactRequired: true,
    equipmentChecklist: ["8 Bats", "12 Tennis balls", "Stumps", "Cones"],
    participantChecklist: ["Sports shoes", "Water bottle"],
    weatherDependency: true,
    cancellationThreshold: 6,
    anonymousJoinedCount: false,
    tempIdFormat: "SA-##",
    aliasStyle: "AcademyStar",
    teamAssignmentRule: "random",
    revealTimeMinsBefore: 120,
    infoRevealed: ["Coach name", "Station order"],
    infoNeverRevealed: ["Phone number"],
    entryType: "individual",
    competitiveLevel: "beginner",
    createdAt: "2026-08-01",
    updatedAt: "2026-08-01"
  },
  {
    id: "et-8",
    categoryId: "cat-tt",
    name: "Rooftop TT Socials",
    shortDesc: "Paused — rooftop ladder format awaiting venue.",
    fullDesc: "Open-air table tennis ladder social, paused while we secure a weather-safe rooftop venue.",
    objective: "Rotating TT ladder social with weather contingencies.",
    promise: "Minimum 6 games.",
    status: "paused",
    format: "mixed",
    isTournament: false,
    ageMin: 10,
    ageMax: 60,
    verificationRequired: false,
    minParticipants: 6,
    targetParticipants: 8,
    maxParticipants: 8,
    teamSize: 1,
    numTeams: 8,
    spectatorAllowance: 8,
    compSlots: 0,
    blockedSlots: 0,
    duration: 90,
    checkInWindow: 10,
    bookingOpenDays: 3,
    bookingCloseHours: 1,
    revealHoursBefore: 1,
    lateArrivalMins: 5,
    completionBufferMins: 10,
    basePrice: 249,
    taxAmount: 45,
    platformFee: 12,
    venueCost: 600,
    equipmentCost: 100,
    promoEligible: false,
    refundPolicyTemplate: "Full refund 12h prior",
    requiredRoles: ["coordinator"],
    coordinatorsCount: 1,
    refereeRequired: false,
    safetyContactRequired: false,
    equipmentChecklist: ["8 Paddles", "6 Plastic Balls"],
    participantChecklist: ["Comfortable shoes"],
    weatherDependency: true,
    cancellationThreshold: 6,
    anonymousJoinedCount: false,
    tempIdFormat: "TT-##",
    aliasStyle: "PaddlePace",
    teamAssignmentRule: "random",
    revealTimeMinsBefore: 60,
    infoRevealed: ["Ladder position"],
    infoNeverRevealed: ["Phone number"],
    entryType: "individual",
    createdAt: "2026-07-20",
    updatedAt: "2026-07-28"
  }
];

export const SEED_TEMPLATE_VERSIONS: TemplateVersion[] = [
  {
    id: "ver-1",
    templateId: "et-1",
    version: 1,
    changedFields: ["name", "promise", "capacity", "pricing", "status"],
    changedBy: "op-2",
    timestamp: "2026-07-01, 10:00",
    reason: "Initial template definition",
    previousStatus: undefined,
    newStatus: "active",
    snapshot: { name: "Evening Box Cricket Match", maxParticipants: 12, basePrice: 499, status: "active" }
  },
  {
    id: "ver-2",
    templateId: "et-1",
    version: 2,
    changedFields: ["basePrice", "bookingOpenDays"],
    changedBy: "op-2",
    timestamp: "2026-07-22, 14:30",
    reason: "Price adjusted for peak-season demand",
    previousStatus: "active",
    newStatus: "active",
    snapshot: { basePrice: 499, bookingOpenDays: 5, status: "active" }
  },
  {
    id: "ver-3",
    templateId: "et-3",
    version: 1,
    changedFields: ["name", "format", "privacy", "status"],
    changedBy: "op-10",
    timestamp: "2026-06-15, 09:00",
    reason: "Women-only format with anonymity on by default",
    previousStatus: undefined,
    newStatus: "active",
    snapshot: { name: "Women's Social Badminton", format: "women", anonymousJoinedCount: true, status: "active" }
  }
];

/* ---------------------- session builder (deterministic) ---------------------- */

interface SessionSeed {
  id: string;
  templateId: string;
  categoryId: string;
  territoryId: string;
  cityId: string;
  venueId: string;
  playingAreaId: string;
  status: SessionStatus;
  date: string;
  startTime: string;
  max: number;
  min: number;
  base: number;
  /** Crew member id (c-*) of the lead coordinator; "" leaves the slot open. */
  lead: string;
  /** Crew member id (c-*) of the safety contact; "" leaves the slot open. */
  safety: string;
  opts?: Partial<ScheduledSession>;
}

const S = (s: SessionSeed): ScheduledSession => ({
  id: s.id,
  templateId: s.templateId,
  categoryId: s.categoryId,
  territoryId: s.territoryId,
  cityId: s.cityId,
  venueId: s.venueId,
  playingAreaId: s.playingAreaId,
  status: s.status,
  date: s.date,
  startTime: s.startTime,
  duration: 120,
  timezone: "IST",
  recurrence: "none",
  bookingOpensAt: "5 Days ago",
  bookingClosesAt: `${s.date}, 17:00`,
  revealAt: `${s.date}, 18:00`,
  checkInOpensAt: `${s.date}, 18:45`,
  minParticipants: s.min,
  targetParticipants: s.max,
  maxParticipants: s.max,
  compSlots: 0,
  blockedSlots: 0,
  waitlistEnabled: true,
  waitlistOfferExpiryMins: 15,
  basePrice: s.base,
  discountAmount: 0,
  promoEligible: true,
  finalPrice: s.base,
  leadCoordinatorId: s.lead,
  supportingCoordinatorId: "",
  refereeId: "",
  safetyContactId: s.safety,
  equipmentHandlerId: "",
  equipmentChecklist: [],
  weatherRisk: "low",
  cancellationThreshold: s.min,
  ...s.opts
});

export const SEED_SESSIONS: ScheduledSession[] = [
  S({
    id: "s-1", templateId: "et-1", categoryId: "cat-cricket", territoryId: "hvd-central", cityId: "c-hyd", venueId: "v-3", playingAreaId: "pa-4",
    status: "live", date: "Today", startTime: "19:00", max: 12, min: 8, base: 499, lead: "c-1", safety: "c-9",
    opts: { bookingOpensAt: "5 Days ago", bookingClosesAt: "Today, 17:00", revealAt: "Today, 18:00", checkInOpensAt: "Today, 18:45", refereeId: "c-10", weatherRisk: "low", equipmentChecklist: ["2 Bats", "6 Tennis balls", "Stumps set"] }
  }),
  S({
    id: "s-2", templateId: "et-2", categoryId: "cat-badminton", territoryId: "hvd-central", cityId: "c-hyd", venueId: "v-1", playingAreaId: "pa-1",
    status: "full", date: "Today", startTime: "20:00", max: 16, min: 10, base: 349, lead: "c-14", safety: "c-5",
    opts: { bookingOpensAt: "7 Days ago", bookingClosesAt: "Today, 19:00", revealAt: "Today, 18:00", checkInOpensAt: "Today, 19:50", compSlots: 1, equipmentChecklist: ["Shuttles", "Net"] }
  }),
  S({
    id: "s-3", templateId: "et-3", categoryId: "cat-badminton", territoryId: "hvd-central", cityId: "c-hyd", venueId: "v-1", playingAreaId: "pa-2",
    status: "full", date: "Today", startTime: "21:00", max: 12, min: 8, base: 299, lead: "c-1", safety: "c-9",
    opts: { equipmentChecklist: ["Shuttles", "Net"] }
  }),
  S({
    id: "s-4", templateId: "et-4", categoryId: "cat-tt", territoryId: "hvd-central", cityId: "c-hyd", venueId: "v-2", playingAreaId: "pa-3",
    status: "scheduled", date: "Tomorrow", startTime: "17:00", max: 8, min: 6, base: 249, lead: "c-1", safety: "c-9",
    opts: { duration: 90, equipmentChecklist: ["Paddles", "Balls"] }
  }),
  S({
    id: "s-5", templateId: "et-1", categoryId: "cat-cricket", territoryId: "hvd-central", cityId: "c-hyd", venueId: "v-3", playingAreaId: "pa-4",
    status: "draft", date: "Tomorrow", startTime: "07:00", max: 12, min: 8, base: 549, lead: "c-1", safety: "c-9",
    opts: { refereeId: "c-10" }
  }),
  S({
    id: "s-6", templateId: "et-1", categoryId: "cat-cricket", territoryId: "blr-south", cityId: "c-blr", venueId: "v-4", playingAreaId: "pa-5",
    status: "live", date: "Today", startTime: "19:30", max: 12, min: 8, base: 549, lead: "c-4", safety: "c-12",
    opts: { weatherRisk: "medium" }
  }),
  S({
    id: "s-7", templateId: "et-5", categoryId: "cat-board", territoryId: "blr-south", cityId: "c-blr", venueId: "v-5", playingAreaId: "pa-6",
    status: "scheduled", date: "Today", startTime: "20:00", max: 10, min: 4, base: 199, lead: "", safety: "",
    opts: { duration: 180 }
  }),
  S({
    id: "s-8", templateId: "et-1", categoryId: "cat-cricket", territoryId: "mum-west", cityId: "c-mum", venueId: "v-6", playingAreaId: "pa-7",
    status: "booking-open", date: "Today", startTime: "19:00", max: 14, min: 10, base: 599, lead: "c-15", safety: "c-13",
    
  }),
  S({
    id: "s-9", templateId: "et-3", categoryId: "cat-badminton", territoryId: "mum-west", cityId: "c-mum", venueId: "v-6", playingAreaId: "pa-7",
    status: "check-in-open", date: "Today", startTime: "18:00", max: 12, min: 8, base: 299, lead: "c-11", safety: "c-7",
    opts: { checkInOpensAt: "Today, 17:45" }
  }),
  S({
    id: "s-10", templateId: "et-1", categoryId: "cat-cricket", territoryId: "hvd-central", cityId: "c-hyd", venueId: "v-3", playingAreaId: "pa-4",
    status: "completed", date: "Yesterday", startTime: "19:00", max: 12, min: 8, base: 499, lead: "c-1", safety: "c-9",
    opts: { refereeId: "c-10" }
  }),
  S({
    id: "s-11", templateId: "et-4", categoryId: "cat-tt", territoryId: "hvd-central", cityId: "c-hyd", venueId: "v-2", playingAreaId: "pa-3",
    status: "cancelled", date: "Yesterday", startTime: "20:00", max: 8, min: 6, base: 249, lead: "c-1", safety: "c-9",
    opts: { duration: 90 }
  }),
  S({
    id: "s-12", templateId: "et-5", categoryId: "cat-board", territoryId: "blr-south", cityId: "c-blr", venueId: "v-5", playingAreaId: "pa-6",
    status: "booking-closed", date: "Tomorrow", startTime: "18:00", max: 10, min: 4, base: 199, lead: "c-4", safety: "c-12",
    opts: { duration: 180, bookingClosesAt: "Tomorrow, 16:00" }
  }),
  S({
    id: "s-13", templateId: "et-5", categoryId: "cat-board", territoryId: "blr-south", cityId: "c-blr", venueId: "v-5", playingAreaId: "pa-6",
    status: "booking-open", date: "Today", startTime: "21:00", max: 10, min: 4, base: 199, lead: "c-16", safety: "",
    opts: { duration: 180, bookingOpensAt: "2 Days ago", bookingClosesAt: "Today, 20:00" }
  })
];

/* ---------------------- booking builder (deterministic) ---------------------- */

const B = (
  id: string,
  sessionId: string,
  alias: string,
  tempId: string,
  amount: number,
  rawStatus: string,
  createdAt: string,
  method: string = "card",
  phoneMask: string = "•••• 12",
  waitlistOrder?: number,
  opts: Partial<Booking> = {}
): Booking => {
  let status: BookingStatus = "confirmed";
  let reservationStatus: ReservationStatus = "converted";
  let paymentStatus: PaymentStatus = "confirmed";
  let bookingType: BookingType = "individual";
  let source: BookingSource = "customer-app";

  if (rawStatus === "payment-confirmed" || rawStatus === "checked-in") {
    status = "confirmed";
    reservationStatus = "converted";
    paymentStatus = "confirmed";
  } else if (rawStatus === "payment-pending" || rawStatus === "reserved") {
    status = "payment-pending";
    reservationStatus = "active";
    paymentStatus = "pending";
  } else if (rawStatus === "payment-failed") {
    status = "payment-failed";
    reservationStatus = "released";
    paymentStatus = "failed";
  } else if (rawStatus === "reservation-expired") {
    status = "reservation-expired";
    reservationStatus = "expired";
    paymentStatus = "not-started";
  } else if (rawStatus === "waitlist-joined") {
    status = "waitlisted";
    reservationStatus = "none";
    paymentStatus = "not-started";
  } else if (rawStatus === "waitlist-offered") {
    status = "waitlist-offered";
    reservationStatus = "offer-hold";
    paymentStatus = "not-started";
  } else if (rawStatus === "complimentary") {
    status = "confirmed";
    reservationStatus = "converted";
    paymentStatus = "none";
    bookingType = "complimentary";
    source = "complimentary";
  } else if (rawStatus === "no-show") {
    status = "no-show";
    reservationStatus = "converted";
    paymentStatus = "confirmed";
  } else if (rawStatus === "cancelled" || rawStatus === "cancelled-company") {
    status = rawStatus === "cancelled" ? "cancelled-user" : "cancelled-company";
    reservationStatus = "released";
    paymentStatus = "refunded";
  }

  const bookingCode = `BK-${id.toUpperCase().replace("-", "")}`;

  return {
    id,
    bookingCode,
    sessionId,
    participantId: `usr-${alias.toLowerCase()}`,
    alias,
    phoneMask,
    tempId,
    source,
    bookingType,
    reservationStatus,
    paymentStatus,
    status,
    amount,
    discount: 0,
    tax: Math.round(amount * 0.18),
    platformFee: Math.round(amount * 0.05),
    finalAmount: amount,
    method: bookingType === "complimentary" ? "complimentary" : method,
    paymentReference: paymentStatus === "confirmed" || paymentStatus === "refunded" ? seedPaymentReference(id, method) : undefined,
    reservedAt: createdAt,
    confirmedAt: status === "confirmed" || status === "no-show" ? createdAt : undefined,
    cancellationReason: status === "cancelled-company" ? "Session cancelled: venue power outage" : status === "cancelled-user" ? "Customer schedule conflict" : undefined,
    waitlistOrder,
    waitlistPosition: waitlistOrder,
    checkedIn: rawStatus === "checked-in",
    noShow: rawStatus === "no-show",
    createdAt,
    updatedAt: createdAt,
    createdBy: source === "customer-app" ? "customer" : "op-5",
    ...opts
  };
};

/** Deterministic manual payment reference (payment provider not connected). */
function seedPaymentReference(id: string, method: string): string {
  const n = [...id].reduce((a, c) => (a * 31 + c.charCodeAt(0)) % 1_000_000, 7);
  return method === "upi" ? `UTR${String(40_000_000 + n * 37).padStart(12, "4")}` : `POS-${String(n).padStart(6, "0")}`;
}

/** A hold created shortly before the workspace was seeded, so its countdown is live. */
const SEED_HOLD_START = new Date(Date.now() - 3 * 60_000).toISOString();
const SEED_HOLD_EXPIRY = new Date(Date.now() + 12 * 60_000).toISOString();
const SEED_OFFER_EXPIRY_1 = new Date(Date.now() + 9 * 60_000).toISOString();
const SEED_OFFER_EXPIRY_2 = new Date(Date.now() + 14 * 60_000).toISOString();

export const SEED_BOOKINGS: Booking[] = [
  // s-1 — Evening Box Cricket (live)
  B("b-1", "s-1", "BlazerFox", "CR-01", 499, "payment-confirmed", "Today, 12:10", "card", "•••• 42"),
  B("b-2", "s-1", "MidnightDrive", "CR-02", 499, "payment-confirmed", "Today, 12:15", "card", "•••• 11"),
  B("b-3", "s-1", "CourtPirate", "CR-03", 499, "checked-in", "Today, 12:20", "card", "•••• 07"),
  B("b-4", "s-1", "SilentRally", "CR-04", 499, "payment-confirmed", "Today, 12:25", "card", "•••• 88"),
  B("b-5", "s-1", "CoverDrive", "CR-05", 499, "checked-in", "Today, 13:02", "upi", "•••• 05"),
  B("b-6", "s-1", "DuckHunt", "CR-06", 499, "payment-confirmed", "Today, 13:10", "upi", "•••• 73"),
  B("b-7", "s-1", "NetRunner", "CR-07", 499, "payment-confirmed", "Today, 13:25", "card", "•••• 21"),
  B("b-8", "s-1", "LateCut", "CR-08", 499, "payment-confirmed", "Today, 14:01", "upi", "•••• 19"),
  B("b-w1", "s-1", "SquareTurn", "", 499, "waitlist-joined", "Today, 14:10", "card", "•••• 62", 1),
  // s-2 — Night Badminton League (booking-open, high demand)
  B("b-10", "s-2", "AceServe", "BM-01", 349, "payment-confirmed", "Today, 09:00", "card", "•••• 99"),
  B("b-11", "s-2", "DropShot", "BM-02", 349, "payment-confirmed", "Today, 09:12", "upi", "•••• 88"),
  B("b-12", "s-2", "NetCord", "BM-03", 349, "payment-confirmed", "Today, 09:20", "card", "•••• 77"),
  B("b-13", "s-2", "SmashOrder", "BM-04", 349, "payment-confirmed", "Today, 09:33", "card", "•••• 66"),
  B("b-14", "s-2", "FeatherStorm", "BM-05", 349, "payment-confirmed", "Today, 10:01", "upi", "•••• 55"),
  B("b-15", "s-2", "LobItLow", "BM-06", 349, "payment-confirmed", "Today, 10:15", "card", "•••• 44"),
  B("b-16", "s-2", "PaddlePace", "BM-07", 349, "payment-confirmed", "Today, 10:40", "upi", "•••• 33"),
  B("b-17", "s-2", "SpinDoctor", "BM-08", 349, "payment-confirmed", "Today, 11:05", "card", "•••• 22"),
  B("b-18", "s-2", "DeejayDuo", "BM-09", 349, "payment-confirmed", "Today, 11:20", "card", "•••• 31"),
  B("b-19", "s-2", "Backline", "BM-10", 349, "payment-confirmed", "Today, 11:44", "upi", "•••• 30"),
  B("b-20", "s-2", "FeatherTrappers", "BM-11", 349, "payment-confirmed", "Today, 12:10", "card", "•••• 29"),
  B("b-21", "s-2", "HalfSmashers", "BM-12", 349, "payment-confirmed", "Today, 12:31", "upi", "•••• 28"),
  B("b-22", "s-2", "CrossCourt", "", 349, "payment-pending", "Today, 12:55", "card", "•••• 27", undefined, { method: undefined, reservedAt: SEED_HOLD_START, reservationExpiresAt: SEED_HOLD_EXPIRY }),
  B("b-23", "s-2", "CourtMovers", "BM-14", 0, "complimentary", "Today, 13:02", "internal", "•••• 26"),
  B("b-w2", "s-2", "TheBaseline", "", 349, "waitlist-offered", "Today, 13:20", "card", "•••• 25", 1, { method: undefined, waitlistOfferedAt: SEED_HOLD_START, waitlistOfferExpiresAt: SEED_OFFER_EXPIRY_1 }),
  B("b-w3", "s-2", "OverheadOnly", "", 349, "waitlist-offered", "Today, 13:28", "card", "•••• 24", 2, { method: undefined, waitlistOfferedAt: SEED_HOLD_START, waitlistOfferExpiresAt: SEED_OFFER_EXPIRY_2 }),
  // s-3 — Women's Social Badminton (full)
  B("b-30", "s-3", "AriaServ", "WBM-01", 299, "payment-confirmed", "Today, 08:10", "upi", "•••• 41"),
  B("b-31", "s-3", "SanaSmash", "WBM-02", 299, "payment-confirmed", "Today, 08:22", "card", "•••• 40"),
  B("b-32", "s-3", "MiraSpin", "WBM-03", 299, "payment-confirmed", "Today, 08:35", "card", "•••• 39"),
  B("b-33", "s-3", "TaraDrive", "WBM-04", 299, "payment-confirmed", "Today, 08:48", "upi", "•••• 38"),
  B("b-34", "s-3", "NehaDrop", "WBM-05", 299, "payment-confirmed", "Today, 09:02", "card", "•••• 37"),
  B("b-35", "s-3", "RiyaNet", "WBM-06", 299, "payment-confirmed", "Today, 09:15", "upi", "•••• 36"),
  B("b-36", "s-3", "PoojaLob", "WBM-07", 299, "payment-confirmed", "Today, 09:29", "card", "•••• 35"),
  B("b-37", "s-3", "AnuSmash", "WBM-08", 299, "payment-confirmed", "Today, 09:44", "upi", "•••• 34"),
  B("b-38", "s-3", "KavyaCourt", "WBM-09", 299, "payment-confirmed", "Today, 10:01", "card", "•••• 33"),
  B("b-39", "s-3", "IshaRally", "WBM-10", 299, "payment-confirmed", "Today, 10:18", "upi", "•••• 32"),
  B("b-40", "s-3", "DeepaServe", "WBM-11", 299, "payment-confirmed", "Today, 10:33", "card", "•••• 31"),
  B("b-41", "s-3", "ZoyaCross", "WBM-12", 299, "payment-confirmed", "Today, 10:50", "upi", "•••• 30"),
  // s-6 — Turf Cricket Night (blr, live)
  B("b-42", "s-6", "CoverDrive", "BCR-01", 549, "checked-in", "Today, 14:00", "card", "•••• 61"),
  B("b-43", "s-6", "SilentRally", "BCR-02", 549, "payment-confirmed", "Today, 14:10", "upi", "•••• 60"),
  B("b-44", "s-6", "BlazerFox", "BCR-03", 549, "payment-confirmed", "Today, 14:22", "card", "•••• 59"),
  B("b-45", "s-6", "NetCord", "BCR-04", 549, "checked-in", "Today, 14:35", "card", "•••• 58"),
  B("b-46", "s-6", "DuckHunt", "BCR-05", 549, "payment-confirmed", "Today, 14:48", "upi", "•••• 57"),
  B("b-47", "s-6", "LateCut", "BCR-06", 549, "payment-confirmed", "Today, 15:02", "card", "•••• 56"),
  B("b-w6", "s-6", "SpinDoctor", "", 549, "waitlist-joined", "Today, 15:15", "card", "•••• 55", 1),
  // s-7 — Board Games Parlour (blr, scheduled)
  B("b-48", "s-7", "TabletopKnight", "BG-01", 199, "payment-confirmed", "Today, 11:20", "card", "•••• 54"),
  B("b-49", "s-7", "DiceRoller", "BG-02", 199, "payment-confirmed", "Today, 11:40", "upi", "•••• 53"),
  B("b-50", "s-7", "CardShark", "BG-03", 199, "payment-confirmed", "Today, 12:05", "card", "•••• 52"),
  // s-8 — Mumbai Turf Cricket (booking-open)
  B("b-51", "s-8", "CoverDrive", "MCR-01", 599, "payment-confirmed", "Today, 10:10", "card", "•••• 51"),
  B("b-52", "s-8", "DuckHunt", "MCR-02", 599, "payment-confirmed", "Today, 10:25", "upi", "•••• 50"),
  B("b-53", "s-8", "NetRunner", "MCR-03", 599, "payment-confirmed", "Today, 10:40", "card", "•••• 49"),
  B("b-54", "s-8", "SquareTurn", "MCR-04", 599, "payment-confirmed", "Today, 10:55", "upi", "•••• 48"),
  B("b-55", "s-8", "LateCut", "MCR-05", 599, "payment-confirmed", "Today, 11:12", "card", "•••• 47"),
  B("b-w8", "s-8", "BlazerFox", "", 599, "reservation-expired", "Today, 11:30", "card", "•••• 46", undefined, { method: undefined }),
  B("b-80", "s-8", "FullToss", "", 599, "payment-failed", "Today, 16:40", "upi", "•••• 20"),
  // s-9 — Women's Social Badminton (mum, check-in-open)
  B("b-56", "s-9", "FeatherStorm", "WBM-21", 299, "checked-in", "Today, 13:00", "upi", "•••• 45"),
  B("b-57", "s-9", "LobItLow", "WBM-22", 299, "checked-in", "Today, 13:10", "card", "•••• 44"),
  B("b-58", "s-9", "NetCord", "WBM-23", 299, "payment-confirmed", "Today, 13:22", "card", "•••• 43"),
  B("b-59", "s-9", "DropShot", "WBM-24", 299, "payment-confirmed", "Today, 13:35", "upi", "•••• 42"),
  B("b-60", "s-9", "AceServe", "WBM-25", 299, "payment-confirmed", "Today, 13:50", "card", "•••• 41"),
  B("b-61", "s-9", "PaddlePace", "WBM-26", 299, "payment-confirmed", "Today, 14:05", "upi", "•••• 40"),
  // s-10 — completed cricket (hvd, yesterday)
  B("b-62", "s-10", "BlazerFox", "CR-31", 499, "checked-in", "Yesterday, 10:00", "card", "•••• 39"),
  B("b-63", "s-10", "MidnightDrive", "CR-32", 499, "checked-in", "Yesterday, 10:12", "card", "•••• 38"),
  B("b-64", "s-10", "CourtPirate", "CR-33", 499, "checked-in", "Yesterday, 10:25", "upi", "•••• 37"),
  B("b-65", "s-10", "SilentRally", "CR-34", 499, "checked-in", "Yesterday, 10:40", "card", "•••• 36"),
  B("b-66", "s-10", "CoverDrive", "CR-35", 499, "checked-in", "Yesterday, 10:52", "upi", "•••• 35"),
  B("b-67", "s-10", "DuckHunt", "CR-36", 499, "checked-in", "Yesterday, 11:05", "card", "•••• 34"),
  B("b-68", "s-10", "NetRunner", "CR-37", 499, "checked-in", "Yesterday, 11:18", "upi", "•••• 33"),
  B("b-69", "s-10", "LateCut", "CR-38", 499, "checked-in", "Yesterday, 11:30", "card", "•••• 32"),
  B("b-70", "s-10", "SquareTurn", "CR-39", 499, "no-show", "Yesterday, 11:44", "card", "•••• 31"),
  B("b-71", "s-10", "SpinDoctor", "CR-40", 499, "cancelled", "Yesterday, 12:00", "upi", "•••• 30"),
  // s-11 — cancelled TT (hvd, yesterday)
  B("b-72", "s-11", "PaddlePace", "TT-11", 249, "cancelled-company", "Yesterday, 09:00", "card", "•••• 29"),
  B("b-73", "s-11", "SpinDoctor", "TT-12", 249, "cancelled-company", "Yesterday, 09:15", "upi", "•••• 28"),
  B("b-74", "s-11", "NetRunner", "TT-13", 249, "cancelled-company", "Yesterday, 09:30", "card", "•••• 27", undefined, { paymentStatus: "refund-pending" }),
  B("b-75", "s-11", "DeejayDuo", "TT-14", 249, "cancelled-company", "Yesterday, 09:44", "card", "•••• 26", undefined, { paymentStatus: "refund-pending" }),
  // s-12 — board games (blr, booking-closed)
  B("b-76", "s-12", "CardShark", "BG-11", 199, "payment-confirmed", "Yesterday, 16:00", "card", "•••• 25"),
  B("b-77", "s-12", "DiceRoller", "BG-12", 199, "payment-confirmed", "Yesterday, 16:20", "upi", "•••• 24"),
  B("b-78", "s-12", "TileRunner", "BG-13", 199, "payment-confirmed", "Yesterday, 16:40", "card", "•••• 23"),
  B("b-79", "s-12", "Counters", "BG-14", 199, "payment-confirmed", "Yesterday, 17:02", "upi", "•••• 22")
];

export const SEED_CREW: CrewMember[] = [
  { id: "c-1", territoryId: "hvd-central", venueId: "v-1", name: "Aisha Khan", role: "coordinator", status: "checked-in", assignment: "Lead — Night Badminton League" },
  { id: "c-2", territoryId: "hvd-central", venueId: "v-3", name: "Rohit Nair", role: "staff", status: "checked-in", assignment: "Referee — Evening Box Cricket" },
  { id: "c-3", territoryId: "hvd-central", venueId: "v-3", name: "Tanvi Iyer", role: "staff", status: "checked-in", assignment: "Check-in — Evening Box Cricket" },
  { id: "c-4", territoryId: "blr-south", venueId: "v-4", name: "Sahil Batra", role: "coordinator", status: "assigned", assignment: "Lead — Turf Cricket Night" },
  { id: "c-5", territoryId: "hvd-central", venueId: "v-1", name: "Divya Reddy", role: "staff", status: "assigned", assignment: "Safety contact — Badminton doubles" },
  { id: "c-6", territoryId: "hvd-central", venueId: "v-2", name: "Arjun Mehta", role: "venue-manager", status: "checked-in", assignment: "Venue Manager — Indoor Club" },
  { id: "c-7", territoryId: "mum-west", venueId: "v-6", name: "Sana Sheikh", role: "staff", status: "assigned", assignment: "Equipment — Turf Cricket" },
  { id: "c-8", territoryId: "mum-west", venueId: "v-6", name: "Kabir Rao", role: "staff", status: "available", assignment: "Floor support — Mumbai" },
  { id: "c-9", territoryId: "hvd-central", venueId: "v-1", name: "Priya Menon", role: "safety", status: "checked-in", assignment: "Safety contact — Hyderabad Central" },
  { id: "c-10", territoryId: "hvd-central", venueId: "v-3", name: "Ravi Teja", role: "ops-manager", status: "assigned", assignment: "Referee — Evening Box Cricket" },
  { id: "c-11", territoryId: "mum-west", venueId: "v-6", name: "Neha Kulkarni", role: "coordinator", status: "assigned", assignment: "Lead — Mumbai badminton" },
  { id: "c-12", territoryId: "blr-south", venueId: "v-4", name: "Farhan Ali", role: "safety", status: "assigned", assignment: "Safety contact — Bengaluru South" },
  { id: "c-13", territoryId: "mum-west", venueId: "v-6", name: "Meghna Das", role: "safety", status: "assigned", assignment: "Safety contact — Mumbai West" },
  { id: "c-14", territoryId: "hvd-central", venueId: "v-1", name: "Rahul Varma", role: "coordinator", status: "assigned", assignment: "Lead — Badminton doubles" },
  { id: "c-15", territoryId: "mum-west", venueId: "v-6", name: "Imran Qureshi", role: "coordinator", status: "assigned", assignment: "Lead — Turf cricket" },
  { id: "c-16", territoryId: "blr-south", venueId: "v-5", name: "Lakshmi Iyer", role: "coordinator", status: "assigned", assignment: "Lead — Board game night" }
];

export const SEED_SHIFTS: Shift[] = [
  { id: "sh-1", crewId: "c-1", venueId: "v-1", zone: "Night League", from: "19:00", to: "23:00" },
  { id: "sh-2", crewId: "c-2", venueId: "v-3", zone: "Box Cricket", from: "18:30", to: "22:30" },
  { id: "sh-3", crewId: "c-3", venueId: "v-3", zone: "Check-in", from: "18:30", to: "22:30" },
  { id: "sh-4", crewId: "c-4", venueId: "v-4", zone: "Turf Cricket", from: "19:00", to: "23:00" },
  { id: "sh-5", crewId: "c-5", venueId: "v-1", zone: "Safety watch", from: "19:30", to: "23:30" },
  { id: "sh-6", crewId: "c-6", venueId: "v-2", zone: "Venue floor", from: "18:00", to: "23:00" },
  { id: "sh-7", crewId: "c-7", venueId: "v-6", zone: "Equipment", from: "18:00", to: "22:00" }
];

/** ISO timestamp `minutes` from now (negative = in the past). Keeps seeded safety and tournament times current. */
const seedAt = (minutes: number): string => new Date(Date.now() + minutes * 60_000).toISOString();

export const SEED_TOURNAMENTS: Tournament[] = [
  {
    id: "tr-1",
    name: "Sunday Cricket Knockout",
    code: "SCK-2026",
    experienceTemplateId: "et-1",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    venueId: "v-3",
    playingAreaIds: ["pa-4"],
    sessionIds: ["s-10"],
    format: "single-elimination",
    status: "published",
    teamIds: ["tr-1-team-1", "tr-1-team-2", "tr-1-team-3", "tr-1-team-4"],
    entrants: [
      { id: "tr-1-team-1", name: "Ravi's XI", seed: 1, status: "active" },
      { id: "tr-1-team-2", name: "Midnight Drive", seed: 2, status: "active" },
      { id: "tr-1-team-3", name: "Net Runners", seed: 3, status: "active" },
      { id: "tr-1-team-4", name: "Smash Order", seed: 4, status: "active" }
    ],
    minimumTeams: 4,
    maximumTeams: 8,
    matchDuration: 30,
    breakDuration: 10,
    seedingMethod: "seeded",
    verificationRequirement: "referee",
    prizePlaceholder: "Winner trophy + ₹5,000 voucher",
    registrationClosesAt: seedAt(20 * 60),
    scheduledStart: seedAt(26 * 60),
    createdBy: "op-5",
    createdAt: seedAt(-2 * 24 * 60),
    updatedAt: seedAt(-5 * 60)
  },
  {
    id: "tr-2",
    name: "Badminton Masters Cup",
    code: "BMC-2026",
    experienceTemplateId: "et-3",
    territoryId: "blr-south",
    cityId: "c-blr",
    venueId: "v-4",
    playingAreaIds: ["pa-5"],
    sessionIds: [],
    format: "single-elimination",
    status: "live",
    teamIds: ["tr-2-team-1", "tr-2-team-2", "tr-2-team-3", "tr-2-team-4"],
    entrants: [
      { id: "tr-2-team-1", name: "Smash Order", seed: 1, status: "active" },
      { id: "tr-2-team-2", name: "Net Kings", seed: 4, status: "active" },
      { id: "tr-2-team-3", name: "Featherstorm", seed: 2, status: "active" },
      { id: "tr-2-team-4", name: "Backline", seed: 3, status: "active" }
    ],
    minimumTeams: 4,
    maximumTeams: 8,
    matchDuration: 20,
    breakDuration: 5,
    seedingMethod: "seeded",
    verificationRequirement: "dual",
    prizePlaceholder: "Champion medals + venue credits",
    registrationClosesAt: seedAt(-5 * 60),
    scheduledStart: seedAt(-60),
    actualStart: seedAt(-55),
    createdBy: "op-2",
    createdAt: seedAt(-7 * 24 * 60),
    updatedAt: seedAt(-10)
  },
  {
    id: "tr-3",
    name: "Weekend Futsal Championship",
    code: "WFC-2026",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    venueId: "v-1",
    playingAreaIds: ["pa-1", "pa-2"],
    sessionIds: [],
    format: "single-elimination",
    status: "draft",
    teamIds: ["tr-3-team-1", "tr-3-team-2", "tr-3-team-3", "tr-3-team-4", "tr-3-team-5"],
    entrants: [
      { id: "tr-3-team-1", name: "Gully Boyz", seed: 1, status: "active" },
      { id: "tr-3-team-2", name: "Court Pirates", seed: 2, status: "active" },
      { id: "tr-3-team-3", name: "Super Strikers", seed: 3, status: "active" },
      { id: "tr-3-team-4", name: "Apex Smashers", seed: 4, status: "active" },
      { id: "tr-3-team-5", name: "Spin Kings", seed: 5, status: "active" }
    ],
    minimumTeams: 4,
    maximumTeams: 8,
    matchDuration: 25,
    breakDuration: 10,
    seedingMethod: "random",
    verificationRequirement: "dual",
    prizePlaceholder: "Trophy for the winning team",
    registrationClosesAt: seedAt(4 * 24 * 60),
    scheduledStart: seedAt(5 * 24 * 60),
    createdBy: "op-1",
    createdAt: seedAt(-6 * 60),
    updatedAt: seedAt(-6 * 60)
  }
];

export const SEED_TOURNAMENT_MATCHES: TournamentMatch[] = [
  /* tr-1: Sunday Cricket Knockout — published, semi-finals scheduled for tomorrow */
  {
    id: "m-1",
    tournamentId: "tr-1",
    roundNumber: 1,
    matchNumber: 1,
    roundLabel: "Semi-finals",
    teamAId: "tr-1-team-1",
    teamBId: "tr-1-team-4",
    playingAreaId: "pa-4",
    refereeId: "c-2",
    status: "scheduled",
    scheduledAt: seedAt(26 * 60),
    nextMatchId: "m-5",
    createdAt: seedAt(-2 * 24 * 60),
    updatedAt: seedAt(-2 * 24 * 60)
  },
  {
    id: "m-2",
    tournamentId: "tr-1",
    roundNumber: 1,
    matchNumber: 2,
    roundLabel: "Semi-finals",
    teamAId: "tr-1-team-2",
    teamBId: "tr-1-team-3",
    playingAreaId: "pa-4",
    status: "scheduled",
    scheduledAt: seedAt(26 * 60 + 40),
    nextMatchId: "m-5",
    createdAt: seedAt(-2 * 24 * 60),
    updatedAt: seedAt(-2 * 24 * 60)
  },
  {
    id: "m-5",
    tournamentId: "tr-1",
    roundNumber: 2,
    matchNumber: 1,
    roundLabel: "Final",
    playingAreaId: "pa-4",
    refereeId: "c-2",
    status: "scheduled",
    scheduledAt: seedAt(26 * 60 + 80),
    createdAt: seedAt(-2 * 24 * 60),
    updatedAt: seedAt(-2 * 24 * 60)
  },
  /* tr-2: Badminton Masters Cup — live; first semi verified, second semi in play */
  {
    id: "m-3",
    tournamentId: "tr-2",
    roundNumber: 1,
    matchNumber: 1,
    roundLabel: "Semi-finals",
    teamAId: "tr-2-team-1",
    teamBId: "tr-2-team-2",
    playingAreaId: "pa-5",
    refereeId: "c-4",
    status: "verified",
    scoreA: 21,
    scoreB: 14,
    winnerTeamId: "tr-2-team-1",
    resultType: "score",
    resultRevisions: [
      { revisionNumber: 1, scoreA: 21, scoreB: 14, winnerTeamId: "tr-2-team-1", resultType: "score", recordedBy: "op-7", recordedAt: seedAt(-28), verifiedBy: "op-5", verifiedAt: seedAt(-26) }
    ],
    startedAt: seedAt(-55),
    endedAt: seedAt(-28),
    verifiedAt: seedAt(-26),
    verifiedBy: "op-5",
    scheduledAt: seedAt(-60),
    nextMatchId: "m-6",
    createdAt: seedAt(-7 * 24 * 60),
    updatedAt: seedAt(-26)
  },
  {
    id: "m-4",
    tournamentId: "tr-2",
    roundNumber: 1,
    matchNumber: 2,
    roundLabel: "Semi-finals",
    teamAId: "tr-2-team-3",
    teamBId: "tr-2-team-4",
    playingAreaId: "pa-5",
    refereeId: "c-4",
    status: "live",
    startedAt: seedAt(-20),
    scheduledAt: seedAt(-25),
    nextMatchId: "m-6",
    createdAt: seedAt(-7 * 24 * 60),
    updatedAt: seedAt(-20)
  },
  {
    id: "m-6",
    tournamentId: "tr-2",
    roundNumber: 2,
    matchNumber: 1,
    roundLabel: "Final",
    teamAId: "tr-2-team-1",
    playingAreaId: "pa-5",
    refereeId: "c-4",
    status: "scheduled",
    scheduledAt: seedAt(15),
    createdAt: seedAt(-7 * 24 * 60),
    updatedAt: seedAt(-26)
  }
];

/** Manual ledger entries (promotions and adjustments). Payment and refund rows are derived — see SEED_TRANSACTIONS. */
const SEED_MANUAL_TRANSACTIONS: Transaction[] = [
  { id: "t-5", sessionId: "s-2", territoryId: "hvd-central", bookingId: "b-12", kind: "promo", amount: -90, method: "promo", status: "pending", at: "Today, 19:01" },
  { id: "t-7", sessionId: "s-3", territoryId: "hvd-central", bookingId: "b-30", kind: "adjustment", amount: -25, method: "adjustment", status: "pending", at: "Today, 19:10" }
];

export const SEED_INCIDENTS: Incident[] = [
  {
    id: "i-1",
    incidentCode: "INC-HVD-001",
    sessionId: "s-1",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    venueId: "v-3",
    category: "equipment",
    severity: "medium",
    status: "acknowledged",
    reportedBy: "op-7",
    reportedAt: seedAt(-42),
    occurredAt: seedAt(-45),
    acknowledgedAt: seedAt(-38),
    acknowledgedBy: "op-5",
    participantTemporaryIds: ["CR-01"],
    staffIds: ["op-7"],
    immediateAction: "Replaced cricket bat with a spare from the kit",
    medicalAssistance: false,
    venueEscalated: false,
    evidenceItemIds: ["ev-1", "ev-2"],
    notes: "Bat handle broke during a cover drive. No one was hurt; play resumed after the swap.",
    createdAt: seedAt(-42),
    updatedAt: seedAt(-38)
  },
  {
    id: "i-2",
    incidentCode: "INC-MUM-001",
    sessionId: "s-8",
    territoryId: "mum-west",
    cityId: "c-mum",
    venueId: "v-6",
    category: "crowd",
    severity: "low",
    status: "triaged",
    reportedBy: "op-7",
    reportedAt: seedAt(-75),
    occurredAt: seedAt(-80),
    acknowledgedAt: seedAt(-72),
    acknowledgedBy: "op-9",
    triagedAt: seedAt(-70),
    triagedBy: "op-9",
    participantTemporaryIds: [],
    staffIds: ["op-7"],
    immediateAction: "Opened a second check-in lane",
    medicalAssistance: false,
    venueEscalated: false,
    followUpOwnerId: "op-3",
    followUpDueAt: seedAt(24 * 60),
    notes: "Crowding near the check-in desk before the session started.",
    triageSeverityReview: "Severity confirmed as low",
    triageImmediateRisk: "None — queue only",
    triageVenueImpact: "Minimal",
    triageRecommendation: "Add a second check-in lane for sessions above 20 participants.",
    createdAt: seedAt(-75),
    updatedAt: seedAt(-70)
  },
  {
    id: "i-3",
    incidentCode: "INC-HVD-002",
    sessionId: "s-11",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    venueId: "v-2",
    category: "weather",
    severity: "high",
    status: "closed",
    reportedBy: "op-4",
    reportedAt: seedAt(-26 * 60),
    occurredAt: seedAt(-26 * 60 - 30),
    acknowledgedAt: seedAt(-26 * 60 + 5),
    acknowledgedBy: "op-4",
    triagedAt: seedAt(-26 * 60 + 10),
    triagedBy: "op-9",
    participantTemporaryIds: [],
    staffIds: ["op-4"],
    immediateAction: "Cancelled the session and queued refunds",
    medicalAssistance: false,
    venueEscalated: true,
    investigatorId: "op-9",
    resolution: "Session cancelled under the weather policy; every booking refunded through the standard refund flow.",
    resolvedAt: seedAt(-25 * 60),
    resolvedBy: "op-9",
    closedAt: seedAt(-24 * 60),
    closedBy: "op-9",
    evidenceItemIds: ["ev-3"],
    notes: "Rooftop table tennis cancelled due to rain and lightning.",
    triageSeverityReview: "Severity confirmed as high",
    triageImmediateRisk: "Lightning risk on the rooftop",
    triageRecommendation: "Cancel the session and refund every booking under the weather policy.",
    createdAt: seedAt(-26 * 60),
    updatedAt: seedAt(-24 * 60)
  },
  {
    id: "i-4",
    incidentCode: "INC-HVD-003",
    sessionId: "s-10",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    venueId: "v-3",
    category: "injury",
    severity: "medium",
    status: "resolved",
    reportedBy: "op-7",
    reportedAt: seedAt(-17 * 60),
    occurredAt: seedAt(-17 * 60 - 5),
    acknowledgedAt: seedAt(-17 * 60 + 5),
    acknowledgedBy: "op-7",
    triagedAt: seedAt(-17 * 60 + 10),
    triagedBy: "op-5",
    participantTemporaryIds: ["CR-35"],
    staffIds: ["op-7", "op-4"],
    immediateAction: "Applied an ice pack and monitored the participant",
    medicalAssistance: false,
    venueEscalated: false,
    investigatorId: "op-9",
    resolution: "Participant recovered on site and walked out unassisted. No further action needed.",
    resolvedAt: seedAt(-16 * 60),
    resolvedBy: "op-9",
    evidenceItemIds: ["ev-4"],
    notes: "Minor ankle twist during the final over.",
    triageSeverityReview: "Severity confirmed as medium",
    triageImmediateRisk: "Low — participant alert and weight-bearing",
    triageRecommendation: "Monitor for 30 minutes and record the first-aid assessment.",
    createdAt: seedAt(-17 * 60),
    updatedAt: seedAt(-16 * 60)
  },
  {
    id: "i-5",
    incidentCode: "INC-BLR-001",
    tournamentId: "tr-2",
    matchId: "m-3",
    territoryId: "blr-south",
    cityId: "c-blr",
    venueId: "v-4",
    category: "misconduct",
    severity: "high",
    status: "investigating",
    reportedBy: "op-7",
    reportedAt: seedAt(-40),
    occurredAt: seedAt(-42),
    acknowledgedAt: seedAt(-38),
    acknowledgedBy: "op-9",
    triagedAt: seedAt(-35),
    triagedBy: "op-9",
    participantTemporaryIds: ["BD-12"],
    staffIds: ["op-7"],
    immediateAction: "Verbal warning issued and the match paused briefly",
    medicalAssistance: false,
    venueEscalated: false,
    investigatorId: "op-9",
    evidenceItemIds: ["ev-5", "ev-6"],
    notes: "Player BD-12 argued aggressively with the referee after a disputed line call in the semi-final.",
    triageSeverityReview: "Severity confirmed as high",
    triageImmediateRisk: "Repeat confrontation possible if BD-12 plays again today",
    triageRecommendation: "Open a moderation case and consider a formal warning before the final.",
    createdAt: seedAt(-40),
    updatedAt: seedAt(-30)
  },
  {
    id: "i-6",
    incidentCode: "INC-HVD-004",
    sessionId: "s-1",
    territoryId: "hvd-central",
    cityId: "c-hyd",
    venueId: "v-3",
    category: "injury",
    severity: "critical",
    status: "reported",
    reportedBy: "op-5",
    reportedAt: seedAt(-22),
    occurredAt: seedAt(-24),
    participantTemporaryIds: ["CR-08"],
    staffIds: ["op-5", "op-4"],
    immediateAction: "Session paused. First aid given and the venue medical team called.",
    medicalAssistance: true,
    venueEscalated: false,
    evidenceItemIds: ["ev-7", "ev-8"],
    notes: "Participant CR-08 was struck on the head by a bat during play. Conscious but dizzy; session paused immediately.",
    createdAt: seedAt(-22),
    updatedAt: seedAt(-22)
  }
];

/* ------------------------------------------------------------------
 * SA-P2H: Evidence register (metadata only — files are kept outside the console)
 * ------------------------------------------------------------------ */

export const SEED_EVIDENCE_ITEMS: EvidenceItem[] = [
  {
    id: "ev-1",
    incidentId: "i-1",
    type: "image-placeholder",
    label: "Broken bat handle photo",
    description: "Close-up of the cracked handle showing the break point.",
    placeholderFileName: "bat_handle_damage.jpg",
    capturedBy: "op-7",
    capturedAt: seedAt(-41),
    sensitivity: "low",
    status: "collected",
    createdAt: seedAt(-41),
    updatedAt: seedAt(-41)
  },
  {
    id: "ev-2",
    incidentId: "i-1",
    type: "staff-note",
    label: "Equipment inspection note",
    description: "Bat was regulation-approved. Handle failure was material fatigue, not misuse.",
    capturedBy: "op-7",
    capturedAt: seedAt(-39),
    sensitivity: "low",
    status: "reviewed",
    createdAt: seedAt(-39),
    updatedAt: seedAt(-35)
  },
  {
    id: "ev-3",
    incidentId: "i-3",
    type: "venue-report",
    label: "Weather cancellation report",
    description: "Venue management report confirming unsafe rooftop conditions due to lightning.",
    capturedBy: "op-4",
    capturedAt: seedAt(-26 * 60 + 5),
    sensitivity: "low",
    status: "archived",
    createdAt: seedAt(-26 * 60 + 5),
    updatedAt: seedAt(-24 * 60)
  },
  {
    id: "ev-4",
    incidentId: "i-4",
    type: "medical-placeholder",
    label: "Ankle injury first-aid record",
    description: "First-aid assessment for CR-35. Kept in the venue first-aid log book.",
    placeholderFileName: "Venue first-aid log, page 14",
    capturedBy: "op-7",
    capturedAt: seedAt(-17 * 60 + 5),
    sensitivity: "high",
    status: "collected",
    createdAt: seedAt(-17 * 60 + 5),
    updatedAt: seedAt(-16 * 60)
  },
  {
    id: "ev-5",
    incidentId: "i-5",
    type: "witness-statement",
    label: "Referee statement",
    description: "BD-12 approached aggressively after the line call, raised their voice and used inappropriate language.",
    capturedBy: "op-7",
    capturedAt: seedAt(-38),
    sensitivity: "medium",
    status: "collected",
    createdAt: seedAt(-38),
    updatedAt: seedAt(-38)
  },
  {
    id: "ev-6",
    incidentId: "i-5",
    type: "witness-statement",
    label: "Opposing player statement",
    description: "Confirms BD-12 was aggressive but made no physical contact.",
    capturedBy: "op-7",
    capturedAt: seedAt(-36),
    sensitivity: "medium",
    status: "collected",
    createdAt: seedAt(-36),
    updatedAt: seedAt(-36)
  },
  {
    id: "ev-7",
    incidentId: "i-6",
    type: "medical-placeholder",
    label: "Head injury first-aid log",
    description: "First-responder notes for CR-08. Held by the venue medical team.",
    capturedBy: "op-5",
    capturedAt: seedAt(-21),
    sensitivity: "restricted",
    status: "pending",
    createdAt: seedAt(-21),
    updatedAt: seedAt(-21)
  },
  {
    id: "ev-8",
    incidentId: "i-6",
    type: "image-placeholder",
    label: "Playing area photo",
    description: "Photo of the pitch where the incident happened.",
    placeholderFileName: "pitch1_scene.jpg",
    capturedBy: "op-5",
    capturedAt: seedAt(-20),
    sensitivity: "medium",
    status: "pending",
    createdAt: seedAt(-20),
    updatedAt: seedAt(-20)
  }
];

/* ------------------------------------------------------------------
 * SA-P2H: Disputes
 * ------------------------------------------------------------------ */

export const SEED_DISPUTES: Dispute[] = [
  {
    id: "disp-1",
    type: "match-result",
    status: "under-review",
    reason: "Net Kings say the semi-final score was miscounted: a serve called out in the second game was in.",
    relatedEntityType: "tournament-match",
    relatedEntityId: "m-3",
    tournamentId: "tr-2",
    matchId: "m-3",
    submittedBy: "Net Kings (captain)",
    submittedAt: seedAt(-24),
    recordedBy: "op-7",
    reviewerId: "op-9",
    assignedAt: seedAt(-20),
    notes: "Reviewing the referee's scorecard.",
    createdAt: seedAt(-24),
    updatedAt: seedAt(-20)
  },
  {
    id: "disp-2",
    type: "booking-refund",
    status: "closed",
    reason: "Session s-11 was cancelled due to weather. Customer asks why the refund has not arrived.",
    relatedEntityType: "session",
    relatedEntityId: "s-11",
    sessionId: "s-11",
    bookingId: "b-72",
    submittedBy: "Customer (booking b-72)",
    submittedAt: seedAt(-25 * 60),
    recordedBy: "op-8",
    reviewerId: "op-9",
    assignedAt: seedAt(-25 * 60 + 5),
    decision: "Full refund approved — the session was cancelled by us due to weather.",
    decisionReason: "Weather cancellation policy applies; the customer is eligible for a full refund.",
    decidedBy: "op-9",
    decidedAt: seedAt(-24 * 60 - 30),
    correctionCreated: true,
    correctionId: "rex-1",
    closedAt: seedAt(-24 * 60),
    closedBy: "op-9",
    createdAt: seedAt(-25 * 60),
    updatedAt: seedAt(-24 * 60)
  },
  {
    id: "disp-3",
    type: "participant-conduct",
    status: "evidence-requested",
    reason: "Backline allege unsportsmanlike behaviour from a Featherstorm player during warm-up.",
    relatedEntityType: "tournament",
    relatedEntityId: "tr-2",
    tournamentId: "tr-2",
    submittedBy: "Backline (captain)",
    submittedAt: seedAt(-65),
    recordedBy: "op-7",
    reviewerId: "op-9",
    assignedAt: seedAt(-60),
    evidenceRequested: true,
    evidenceRequestedAt: seedAt(-55),
    notes: "Evidence requested: witness statements from court-side staff.",
    createdAt: seedAt(-65),
    updatedAt: seedAt(-55)
  }
];

/* ------------------------------------------------------------------
 * SA-P2H: Moderation Cases
 * ------------------------------------------------------------------ */

export const SEED_MODERATION_CASES: ModerationCase[] = [
  {
    id: "mod-case-1",
    subjectTemporaryId: "BD-12",
    relatedIncidentIds: ["i-5"],
    relatedTournamentIds: ["tr-2"],
    category: "misconduct",
    severity: "high",
    status: "action-proposed",
    assignedReviewerId: "op-9",
    evidencePlaceholderIds: ["ev-5", "ev-6"],
    recommendedAction: "formal-warning",
    originType: "incident",
    originId: "i-5",
    notes: "Argued aggressively with the referee. First recorded offence for this participant.",
    createdAt: seedAt(-32),
    updatedAt: seedAt(-30)
  },
  {
    id: "mod-case-2",
    subjectTemporaryId: "CR-22",
    relatedIncidentIds: [],
    relatedSessionIds: ["s-1", "s-10"],
    category: "repeated-misconduct",
    severity: "medium",
    status: "action-proposed",
    assignedReviewerId: "op-9",
    previousActionIds: ["mod-act-3"],
    recommendedAction: "temporary-suspension",
    originType: "staff-report",
    originId: "staff-report-001",
    notes: "Third disruptive incident across two sessions. The earlier informal note had no effect.",
    createdAt: seedAt(-8 * 60),
    updatedAt: seedAt(-7 * 60)
  },
  {
    id: "mod-case-3",
    subjectTemporaryId: "CR-17",
    relatedIncidentIds: [],
    relatedSessionIds: ["s-5"],
    category: "safety-violation",
    severity: "medium",
    status: "approved",
    assignedReviewerId: "op-9",
    previousActionIds: ["mod-act-4"],
    decision: "Approved temporary suspension",
    decidedBy: "op-2",
    decidedAt: seedAt(-20 * 24 * 60),
    originType: "staff-report",
    originId: "staff-report-000",
    notes: "Played with metal studs after two reminders. Suspension has since expired.",
    createdAt: seedAt(-21 * 24 * 60),
    updatedAt: seedAt(-20 * 24 * 60)
  }
];

/* ------------------------------------------------------------------
 * SA-P2H: Moderation Actions
 * ------------------------------------------------------------------ */

export const SEED_MODERATION_ACTIONS: ModerationAction[] = [
  {
    id: "mod-act-1",
    caseId: "mod-case-1",
    type: "formal-warning",
    subjectTemporaryId: "BD-12",
    reason: "Aggressive behaviour toward the referee during a tournament match. Verbal warning escalated to a formal warning.",
    evidenceIds: ["ev-5", "ev-6"],
    scope: "tournament",
    scopeEntityId: "tr-2",
    effectiveDate: seedAt(-30),
    status: "proposed",
    createdBy: "op-7",
    createdAt: seedAt(-30),
    updatedAt: seedAt(-30)
  },
  {
    id: "mod-act-2",
    caseId: "mod-case-2",
    type: "temporary-suspension",
    subjectTemporaryId: "CR-22",
    reason: "Third incident of disruptive behaviour. The previous informal note (mod-act-3) was not enough.",
    scope: "territory",
    scopeEntityId: "hvd-central",
    effectiveDate: seedAt(-7 * 60),
    expiryDate: seedAt(7 * 24 * 60),
    status: "proposed",
    createdBy: "op-4",
    createdAt: seedAt(-7 * 60),
    updatedAt: seedAt(-7 * 60)
  },
  {
    id: "mod-act-3",
    caseId: "mod-case-2",
    type: "informal-note",
    subjectTemporaryId: "CR-22",
    reason: "Verbal altercation with another participant during session s-10. Spoke to the participant and noted it.",
    scope: "venue",
    scopeEntityId: "v-3",
    effectiveDate: seedAt(-3 * 24 * 60),
    status: "active",
    approvedBy: "op-9",
    approvedAt: seedAt(-3 * 24 * 60),
    createdBy: "op-7",
    createdAt: seedAt(-3 * 24 * 60),
    updatedAt: seedAt(-3 * 24 * 60)
  },
  {
    id: "mod-act-4",
    caseId: "mod-case-3",
    type: "temporary-suspension",
    subjectTemporaryId: "CR-17",
    reason: "Repeated equipment safety violations (metal studs on turf) after two reminders.",
    scope: "platform",
    effectiveDate: seedAt(-20 * 24 * 60),
    expiryDate: seedAt(-6 * 24 * 60),
    status: "active",
    approvedBy: "op-2",
    approvedAt: seedAt(-20 * 24 * 60),
    createdBy: "op-9",
    createdAt: seedAt(-21 * 24 * 60),
    updatedAt: seedAt(-20 * 24 * 60)
  }
];

/* ------------------------------------------------------------------
 * SA-P2H: Refund Exceptions
 * ------------------------------------------------------------------ */

export const SEED_REFUND_EXCEPTIONS: RefundException[] = [
  {
    id: "rex-1",
    incidentId: "i-3",
    disputeId: "disp-2",
    sessionId: "s-11",
    bookingId: "b-72",
    reason: "safety-incident",
    amount: 249,
    currency: "INR",
    status: "completed",
    recommendedBy: "op-4",
    recommendedAt: "Yesterday, 18:10",
    reviewedBy: "op-1",
    reviewedAt: "Yesterday, 18:20",
    approvedBy: "op-1",
    approvedAt: "Yesterday, 18:25",
    linkedRefundId: "ref-001",
    notes: "Weather cancellation — customer dispute upheld, exception refund approved.",
    createdAt: "Yesterday, 18:10",
    updatedAt: "Yesterday, 18:25"
  },
  {
    id: "rex-2",
    incidentId: "i-6",
    sessionId: "s-1",
    bookingId: "b-8",
    reason: "medical-incident",
    amount: 499,
    currency: "INR",
    status: "recommended",
    recommendedBy: "op-5",
    recommendedAt: "Today, 19:50",
    notes: "Refund recommended for CR-08 booking due to critical head injury during session.",
    createdAt: "Today, 19:50",
    updatedAt: "Today, 19:50"
  }
];

export const SEED_SIGNALS: Signal[] = [
  { id: "sg-1", kind: "join", message: "FeatherStorm joined Night Badminton League", sessionId: "s-2", at: "19:38", read: false },
  { id: "sg-2", kind: "strike", message: "CourtPirate checked in — Evening Box Cricket", sessionId: "s-1", at: "19:29", read: false },
  { id: "sg-3", kind: "alert", message: "Evening Box Cricket is sold out. Waitlist has 1.", sessionId: "s-1", at: "19:20", read: false },
  { id: "sg-4", kind: "join", message: "DuckHunt joined Mumbai Turf Cricket", sessionId: "s-8", at: "19:12", read: true },
  { id: "sg-5", kind: "strike", message: "SilentRally checked in — Evening Box Cricket", sessionId: "s-1", at: "18:58", read: true },
  { id: "sg-6", kind: "close", message: "Weekday Cricket Clash wrapped — 8 of 10 checked in", sessionId: "s-10", at: "Yesterday", read: true },
  { id: "sg-7", kind: "system", message: "Rooftop TT Social cancelled — weather", sessionId: "s-11", at: "Yesterday", read: true },
  { id: "sg-8", kind: "alert", message: "Check-in open on Women's Social Badminton (Mumbai)", sessionId: "s-9", at: "17:55", read: false }
];

export const SEED_AUDITS: AuditEvent[] = [
  { id: "aud-1", sessionId: "s-1", action: "Session Created", operatorId: "op-4", timestamp: "Today, 10:00", description: "Scheduled session created from experience template et-1." },
  { id: "aud-2", sessionId: "s-1", action: "Check-in Strike", operatorId: "op-7", timestamp: "Today, 19:29", description: "Booking b-3 marked checked-in at the door." },
  { id: "aud-3", sessionId: "s-2", action: "Booking Confirmed", operatorId: "op-8", timestamp: "Today, 13:02", description: "Complimentary booking b-23 confirmed for CourtMovers." },
  { id: "aud-4", sessionId: "s-3", action: "Session Marked Full", operatorId: "op-4", timestamp: "Today, 13:30", description: "Session s-3 reached max participants; waitlist enabled." },
  { id: "aud-5", sessionId: undefined, action: "Territory Scope Switched", operatorId: "op-1", timestamp: "Today, 18:40", description: "Operator switched operational scope to Hyderabad Central." }
];

export const SEED_ANALYTICS: DayPoint[] = [
  { label: "Mon", revenue: 12800, bookings: 41, fill: 68 },
  { label: "Tue", revenue: 15100, bookings: 48, fill: 72 },
  { label: "Wed", revenue: 14400, bookings: 44, fill: 70 },
  { label: "Thu", revenue: 18200, bookings: 57, fill: 78 },
  { label: "Fri", revenue: 24100, bookings: 74, fill: 86 },
  { label: "Sat", revenue: 28900, bookings: 88, fill: 91 },
  { label: "Sun", revenue: 26400, bookings: 81, fill: 88 }
];

export const SEED_PROMOS: PromoCode[] = [
  { code: "FIRSTNIGHT", label: "First timer · 20% off", discount: "20%", status: "active" },
  { code: "MIDNIGHT50", label: "Late join · ₹50 off", discount: "₹50", status: "active" },
  { code: "DOUBLESUP", label: "Bring a friend · 15% off", discount: "15%", status: "active" },
  { code: "MONSOON", label: "Rainy night · 25% off", discount: "25%", status: "expired" }
];

/**
 * One payment per paid booking. The payment provider is not connected, so
 * every received payment is a manual record with its method and reference.
 * Yesterday's completed session has been matched against the statement.
 */
export const SEED_PAYMENTS: Payment[] = SEED_BOOKINGS.filter(
  (b) => b.bookingType !== "complimentary" && b.amount > 0 && ["confirmed", "pending", "failed", "refunded", "refund-pending"].includes(String(b.paymentStatus))
).map((b) => {
  const status: Payment["status"] =
    b.paymentStatus === "pending" ? "pending" : b.paymentStatus === "failed" ? "failed" : b.sessionId === "s-10" ? "reconciled" : "confirmed";
  const received = status === "confirmed" || status === "reconciled";
  return {
    id: `pay-${b.id}`,
    bookingId: b.id,
    sessionId: b.sessionId,
    provider: "manual",
    providerReference: received ? b.paymentReference ?? seedPaymentReference(b.id, b.method ?? "card") : undefined,
    amount: b.amount,
    status,
    paymentMethod: received ? b.method || "card" : b.paymentStatus === "failed" ? b.method : undefined,
    initiatedAt: b.reservedAt ?? b.createdAt,
    confirmedAt: received ? b.confirmedAt ?? b.createdAt : undefined,
    failedAt: status === "failed" ? b.createdAt : undefined,
    failureReason: status === "failed" ? "UPI collect request declined by the customer" : undefined,
    createdAt: b.createdAt,
    updatedAt: b.createdAt
  };
});

export const SEED_REFUNDS: Refund[] = [
  {
    id: "ref-001",
    paymentId: "pay-b-72",
    bookingId: "b-72",
    sessionId: "s-11",
    type: "company-cancellation",
    amount: 249,
    reason: "Weather cancellation — customer dispute upheld, exception refund approved.",
    status: "completed",
    requestedAt: "Yesterday, 18:10",
    approvedAt: "Yesterday, 18:25",
    approvedBy: "op-1",
    payoutMethod: "card",
    payoutReference: "RFND-240118",
    completedAt: "Yesterday, 18:40",
    completedBy: "op-6",
    refundExceptionId: "rex-1",
    createdAt: "Yesterday, 18:10",
    updatedAt: "Yesterday, 18:40"
  },
  {
    id: "ref-002",
    paymentId: "pay-b-73",
    bookingId: "b-73",
    sessionId: "s-11",
    type: "company-cancellation",
    amount: 249,
    reason: "Session cancelled: venue power outage",
    status: "completed",
    requestedAt: "Yesterday, 17:05",
    approvedAt: "Yesterday, 17:30",
    approvedBy: "op-6",
    payoutMethod: "upi",
    payoutReference: "UTR884120573311",
    completedAt: "Yesterday, 18:02",
    completedBy: "op-6",
    createdAt: "Yesterday, 17:05",
    updatedAt: "Yesterday, 18:02"
  },
  {
    id: "ref-003",
    paymentId: "pay-b-74",
    bookingId: "b-74",
    sessionId: "s-11",
    type: "company-cancellation",
    amount: 249,
    reason: "Session cancelled: venue power outage",
    status: "approved",
    requestedAt: "Yesterday, 17:05",
    approvedAt: "Yesterday, 17:31",
    approvedBy: "op-6",
    createdAt: "Yesterday, 17:05",
    updatedAt: "Yesterday, 17:31"
  },
  {
    id: "ref-004",
    paymentId: "pay-b-75",
    bookingId: "b-75",
    sessionId: "s-11",
    type: "company-cancellation",
    amount: 249,
    reason: "Session cancelled: venue power outage",
    status: "requested",
    requestedAt: "Yesterday, 17:05",
    createdAt: "Yesterday, 17:05",
    updatedAt: "Yesterday, 17:05"
  },
  {
    id: "ref-005",
    paymentId: "pay-b-71",
    bookingId: "b-71",
    sessionId: "s-10",
    type: "user-cancellation",
    amount: 499,
    reason: "Customer schedule conflict — cancelled more than 24 hours before start",
    status: "completed",
    requestedAt: "Yesterday, 12:00",
    approvedAt: "Yesterday, 12:20",
    approvedBy: "op-6",
    payoutMethod: "upi",
    payoutReference: "UTR884120571904",
    completedAt: "Yesterday, 13:05",
    completedBy: "op-6",
    createdAt: "Yesterday, 12:00",
    updatedAt: "Yesterday, 13:05"
  },
  {
    id: "ref-006",
    paymentId: "pay-b-70",
    bookingId: "b-70",
    sessionId: "s-10",
    type: "user-cancellation",
    amount: 499,
    reason: "Customer asked for a refund after not attending",
    status: "rejected",
    failureReason: "No-show — outside the refund policy",
    requestedAt: "Yesterday, 21:30",
    rejectedAt: "Yesterday, 22:10",
    rejectedBy: "op-6",
    createdAt: "Yesterday, 21:30",
    updatedAt: "Yesterday, 22:10"
  }
];

/** The money ledger view: derived from payments and refunds, plus manual promo/adjustment rows. */
export const SEED_TRANSACTIONS: Transaction[] = buildLedgerTransactions({
  payments: SEED_PAYMENTS,
  refunds: SEED_REFUNDS,
  sessions: SEED_SESSIONS,
  transactions: SEED_MANUAL_TRANSACTIONS
});

export const SEED_IDENTITY_PATTERNS: IdentityPattern[] = [
  {
    id: "pat-cr",
    name: "Cricket Standard",
    prefix: "CR",
    separator: "-",
    numberLength: 2,
    aliasStyle: "StrikeMaster",
    example: "CR-07",
    status: "active",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pat-mx",
    name: "Matrix Arena",
    prefix: "MX",
    separator: "-",
    numberLength: 3,
    aliasStyle: "CyberPulse",
    example: "MX-014",
    status: "active",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pat-night",
    name: "Night Owls",
    prefix: "NIGHT",
    separator: "-",
    numberLength: 2,
    aliasStyle: "NightRider",
    example: "NIGHT-22",
    status: "active",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pat-ember",
    name: "Ember League",
    prefix: "Ember",
    separator: "-",
    numberLength: 2,
    aliasStyle: "EmberFlame",
    example: "Ember-05",
    status: "active",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pat-falcon",
    name: "Falcon Squad",
    prefix: "Falcon",
    separator: "-",
    numberLength: 2,
    aliasStyle: "FalconWing",
    example: "Falcon-12",
    status: "active",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  }
];

export const SEED_TEMPORARY_IDENTITIES: TemporaryIdentity[] = [
  {
    id: "tid-b-1",
    sessionId: "s-1",
    bookingId: "b-1",
    participantAlias: "Rohan V.",
    temporaryCode: "CR-01",
    patternId: "pat-cr",
    generationVersion: 1,
    status: "locked",
    generatedAt: "Today, 10:00",
    lockedAt: "Today, 10:15",
    updatedAt: "Today, 10:15"
  },
  {
    id: "tid-b-2",
    sessionId: "s-1",
    bookingId: "b-2",
    participantAlias: "Anita P.",
    temporaryCode: "CR-02",
    patternId: "pat-cr",
    generationVersion: 1,
    status: "locked",
    generatedAt: "Today, 10:00",
    lockedAt: "Today, 10:15",
    updatedAt: "Today, 10:15"
  },
  {
    id: "tid-b-3",
    sessionId: "s-1",
    bookingId: "b-3",
    participantAlias: "Karan S.",
    temporaryCode: "CR-03",
    patternId: "pat-cr",
    generationVersion: 1,
    status: "locked",
    generatedAt: "Today, 10:00",
    lockedAt: "Today, 10:15",
    updatedAt: "Today, 10:15"
  },
  {
    id: "tid-b-4",
    sessionId: "s-1",
    bookingId: "b-4",
    participantAlias: "Priya M.",
    temporaryCode: "CR-04",
    patternId: "pat-cr",
    generationVersion: 1,
    status: "locked",
    generatedAt: "Today, 10:00",
    lockedAt: "Today, 10:15",
    updatedAt: "Today, 10:15"
  }
];

export const SEED_TEAMS: Team[] = [
  {
    id: "team-s1-a",
    sessionId: "s-1",
    name: "Red Falcons",
    code: "RF",
    capacity: 6,
    status: "locked",
    lockedAt: "Today, 10:30",
    createdAt: "Today, 10:00",
    updatedAt: "Today, 10:30"
  },
  {
    id: "team-s1-b",
    sessionId: "s-1",
    name: "Blue Vipers",
    code: "BV",
    capacity: 6,
    status: "locked",
    lockedAt: "Today, 10:30",
    createdAt: "Today, 10:00",
    updatedAt: "Today, 10:30"
  }
];

export const SEED_TEAM_ASSIGNMENTS: TeamAssignment[] = [
  {
    id: "ta-b-1",
    sessionId: "s-1",
    teamId: "team-s1-a",
    bookingId: "b-1",
    temporaryIdentityId: "tid-b-1",
    assignmentMethod: "random",
    assignedAt: "Today, 10:20",
    status: "active"
  },
  {
    id: "ta-b-2",
    sessionId: "s-1",
    teamId: "team-s1-a",
    bookingId: "b-2",
    temporaryIdentityId: "tid-b-2",
    assignmentMethod: "random",
    assignedAt: "Today, 10:20",
    status: "active"
  },
  {
    id: "ta-b-3",
    sessionId: "s-1",
    teamId: "team-s1-b",
    bookingId: "b-3",
    temporaryIdentityId: "tid-b-3",
    assignmentMethod: "random",
    assignedAt: "Today, 10:20",
    status: "active"
  },
  {
    id: "ta-b-4",
    sessionId: "s-1",
    teamId: "team-s1-b",
    bookingId: "b-4",
    temporaryIdentityId: "tid-b-4",
    assignmentMethod: "random",
    assignedAt: "Today, 10:20",
    status: "active"
  }
];

export const SEED_CHECK_IN_RECORDS: CheckInRecord[] = [
  {
    id: "chk-b-1",
    sessionId: "s-1",
    bookingId: "b-1",
    temporaryIdentityId: "tid-b-1",
    status: "checked-in",
    method: "qr-simulation",
    checkedInAt: "Today, 18:45",
    updatedAt: "Today, 18:45"
  },
  {
    id: "chk-b-2",
    sessionId: "s-1",
    bookingId: "b-2",
    temporaryIdentityId: "tid-b-2",
    status: "checked-in",
    method: "temp-id-search",
    checkedInAt: "Today, 18:50",
    updatedAt: "Today, 18:50"
  },
  {
    id: "chk-b-3",
    sessionId: "s-1",
    bookingId: "b-3",
    temporaryIdentityId: "tid-b-3",
    status: "expected",
    updatedAt: "Today, 18:00"
  },
  {
    id: "chk-b-4",
    sessionId: "s-1",
    bookingId: "b-4",
    temporaryIdentityId: "tid-b-4",
    status: "late",
    method: "manual-override",
    markedLateAt: "Today, 19:10",
    updatedAt: "Today, 19:10"
  }
];

export const SEED_EMERGENCY_ACCESS_LOGS: EmergencyAccessLog[] = [];

export const SEED_LIVE_SESSION_STATES: LiveSessionState[] = [
  {
    id: "lss-s-1",
    sessionId: "s-1",
    status: "Ready",
    accumulatedActiveSeconds: 0,
    emergencyMode: false,
    currentStage: "Pre-session Handover",
    operationalOwnerId: "op-master",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lss-s-2",
    sessionId: "s-2",
    status: "Ready",
    accumulatedActiveSeconds: 0,
    emergencyMode: false,
    currentStage: "Pre-session Handover",
    operationalOwnerId: "op-master",
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_ACTIVITY_SEGMENTS: ActivitySegment[] = [
  {
    id: "seg-s1-1",
    sessionId: "s-1",
    name: "Crew & Safety Briefing",
    type: "Briefing",
    sequence: 1,
    status: "Ready",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "seg-s1-2",
    sessionId: "s-1",
    name: "Warm-Up & Rule Explanation",
    type: "Warm-up",
    sequence: 2,
    status: "Planned",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "seg-s1-3",
    sessionId: "s-1",
    name: "Match 1: Red Falcons vs Blue Vipers",
    type: "Match",
    sequence: 3,
    status: "Planned",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "seg-s1-4",
    sessionId: "s-1",
    name: "Mid-Session Break & Hydration",
    type: "Break",
    sequence: 4,
    status: "Planned",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "seg-s1-5",
    sessionId: "s-1",
    name: "Match 2: Rematch / Final Innings",
    type: "Match",
    sequence: 5,
    status: "Planned",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "seg-s1-6",
    sessionId: "s-1",
    name: "Debrief & Wrap-Up",
    type: "Wrap-up",
    sequence: 6,
    status: "Planned",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_SEGMENT_RESULTS: SegmentResult[] = [];

export const SEED_LIVE_OPERATIONAL_NOTES: LiveOperationalNote[] = [];

export const SEED_EQUIPMENT_CHECK_ITEMS: EquipmentCheckItem[] = [
  {
    id: "eq-s1-1",
    sessionId: "s-1",
    equipmentName: "Standard Leather Box Cricket Balls",
    isCritical: true,
    requiredCount: 6,
    availableCount: 6,
    issuedCount: 6,
    missingCount: 0,
    damagedCount: 0,
    returnedCount: 6,
    status: "returned",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "eq-s1-2",
    sessionId: "s-1",
    equipmentName: "Grade A Willow Cricket Bats",
    isCritical: true,
    requiredCount: 4,
    availableCount: 4,
    issuedCount: 4,
    missingCount: 0,
    damagedCount: 0,
    returnedCount: 4,
    status: "returned",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "eq-s1-3",
    sessionId: "s-1",
    equipmentName: "Wicket Sets & Stumps",
    isCritical: false,
    requiredCount: 2,
    availableCount: 2,
    issuedCount: 2,
    missingCount: 0,
    damagedCount: 0,
    returnedCount: 2,
    status: "returned",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "eq-s1-4",
    sessionId: "s-1",
    equipmentName: "First Aid Kit",
    isCritical: true,
    requiredCount: 1,
    availableCount: 1,
    issuedCount: 1,
    missingCount: 0,
    damagedCount: 0,
    returnedCount: 1,
    status: "returned",
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_SESSION_COMPLETION_SNAPSHOTS: SessionCompletionSnapshot[] = [];
